export interface Template {
  id: string;
  icon: string;
  title: string;
  category: string;
  desc: string;
  source: string;
}

export const TEMPLATES: Template[] = [
  {
    id: "article",
    icon: "📝",
    title: "Academic Article",
    category: "Research",
    desc: "Standard article with abstract, sections, math equations, and bibliography.",
    source: [
      "\\documentclass[12pt,a4paper]{article}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage{amsmath,amssymb,amsthm}",
      "\\usepackage{hyperref}",
      "\\usepackage{geometry}",
      "\\geometry{margin=2.5cm}",
      "",
      "\\title{Title of Your Paper \\\\[0.3em] {\\large Subtitle or Affiliation}}",
      "\\author{First Author\\thanks{Corresponding author: email@university.edu} \\and Second Author}",
      "\\date{\\today}",
      "",
      "\\begin{document}",
      "",
      "\\maketitle",
      "",
      "\\begin{abstract}",
      "This paper presents a study of... Write your abstract here, summarizing the main contributions, methodology, and results. Keep it concise — typically 150–300 words.",
      "\\end{abstract}",
      "",
      "\\section{Introduction}",
      "",
      "Write your introduction here. Reference prior work \\cite{smith2023} and state your contributions clearly.",
      "",
      "\\section{Methodology}",
      "",
      "Describe your methods. You can include equations:",
      "",
      "\\begin{equation}",
      "  E = mc^2",
      "\\end{equation}",
      "",
      "And more complex ones:",
      "",
      "\\[",
      "  \\int_0^\\infty e^{-x^2}\\,dx = \\frac{\\sqrt{\\pi}}{2}",
      "\\]",
      "",
      "\\subsection{Experimental Setup}",
      "",
      "Describe your experimental setup here.",
      "",
      "\\section{Results}",
      "",
      "Present your results. Consider adding tables and figures.",
      "",
      "\\section{Conclusion}",
      "",
      "Summarize your findings and future work.",
      "",
      "\\begin{thebibliography}{9}",
      "\\bibitem{smith2023} Smith, J. (2023). \\textit{A great paper}. Journal of Things, 42(1), 1--10.",
      "\\end{thebibliography}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "cv",
    icon: "👤",
    title: "Academic CV",
    category: "Career",
    desc: "Clean CV with optional photo, university logo, and publications section. Photo slot uses minipage — replace the placeholder with \\includegraphics{photo.jpg}.",
    source: [
      "\\documentclass[11pt,a4paper]{article}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage{geometry}",
      "\\geometry{top=1.5cm, bottom=2cm, left=2cm, right=2cm}",
      "\\usepackage{graphicx}",
      "\\usepackage{hyperref}",
      "\\usepackage{enumitem}",
      "\\usepackage{xcolor}",
      "\\setlist{noitemsep}",
      "\\pagestyle{empty}",
      "",
      "\\definecolor{cvblue}{RGB}{0,56,168}",
      "",
      "\\begin{document}",
      "",
      "% ── Header: name / contact on the left, photo on the right ──────────────",
      "\\begin{minipage}[c]{0.72\\linewidth}",
      "  {\\LARGE\\bfseries Your Full Name}\\\\[0.3em]",
      "  {\\large\\color{cvblue} PhD Student \\textbar{} Machine Learning}\\\\[0.35em]",
      "  \\href{mailto:you@university.edu}{you@university.edu}",
      "  \\quad|\\quad \\href{https://github.com/yourusername}{github.com/yourusername}\\\\",
      "  University Name, Department, City, Country",
      "\\end{minipage}",
      "\\hfill",
      "\\begin{minipage}[c]{0.22\\linewidth}",
      "  \\centering",
      "  % ── REPLACE with your photo ────────────────────────",
      "  % \\includegraphics[width=\\linewidth,clip]{photo.jpg}",
      "  % OR add your university logo:",
      "  % \\includegraphics[height=1.8cm]{university-logo.png}",
      "  % ──────────────────────────────────────────────────",
      "  \\fbox{\\parbox[c][2.8cm][c]{3.1cm}{\\centering{\\color{gray}\\small Photo or Logo\\\\(optional)}}}",
      "\\end{minipage}",
      "",
      "\\vspace{0.35em}",
      "{\\color{cvblue}\\rule{\\linewidth}{1.5pt}}",
      "\\vspace{0.3em}",
      "",
      "\\section*{Education}",
      "",
      "\\textbf{Ph.D. in Computer Science} \\hfill 2020 -- Present\\\\",
      "University Name, City, Country\\\\",
      "\\textit{Thesis: Title of your dissertation}\\\\",
      "Supervisor: Prof.~Name",
      "",
      "\\textbf{M.Sc. in Mathematics} \\hfill 2018 -- 2020\\\\",
      "Another University, City, Country",
      "",
      "\\section*{Research Interests}",
      "",
      "Machine learning, optimization, numerical methods, scientific computing.",
      "",
      "\\section*{Publications}",
      "",
      "\\begin{enumerate}",
      "  \\item \\textbf{Your Name}, Co-Author.",
      "  ``Paper Title.'' \\textit{Journal Name}, vol.~42, 2023.",
      "  \\href{https://doi.org/10.xxxx/xxxx}{\\texttt{doi:...}}",
      "  \\item \\textbf{Your Name}, Co-Author.",
      "  ``Conference Paper.'' In \\textit{NeurIPS}, 2022.",
      "\\end{enumerate}",
      "",
      "\\section*{Research Experience}",
      "",
      "\\textbf{Research Intern} \\hfill Summer 2022\\\\",
      "Company / Lab Name, City\\\\",
      "Worked on relevant problems in the field.",
      "",
      "\\section*{Teaching}",
      "",
      "\\textbf{Teaching Assistant,} Introduction to Machine Learning \\hfill Spring 2023\\\\",
      "Held weekly lab sessions and graded assignments for 60 students.",
      "",
      "\\section*{Skills}",
      "",
      "\\textbf{Programming:} Python, Julia, MATLAB, C++\\\\",
      "\\textbf{Tools:} LaTeX, Git, Linux, Docker, Slurm\\\\",
      "\\textbf{Languages:} English (fluent), French (native)",
      "",
      "\\section*{Awards \\& Grants}",
      "",
      "\\begin{itemize}",
      "  \\item Best Paper Award, SomeConference 2023",
      "  \\item PhD Research Fellowship, University Name, 2021",
      "\\end{itemize}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "beamer",
    icon: "📊",
    title: "Beamer Presentation",
    category: "Slides",
    desc: "Clean Beamer slide deck with title slide, table of contents, and math.",
    source: [
      "\\documentclass{beamer}",
      "\\usetheme{Madrid}",
      "\\usecolortheme{seahorse}",
      "\\usepackage{amsmath,amssymb}",
      "",
      "\\title[Short Title]{Full Title of Your Presentation}",
      "\\subtitle{Subtitle or Conference Name}",
      "\\author{Your Name}",
      "\\institute{University or Department}",
      "\\date{\\today}",
      "",
      "\\begin{document}",
      "",
      "\\begin{frame}",
      "  \\titlepage",
      "\\end{frame}",
      "",
      "\\begin{frame}{Table of Contents}",
      "  \\tableofcontents",
      "\\end{frame}",
      "",
      "\\section{Introduction}",
      "",
      "\\begin{frame}{Motivation}",
      "  \\begin{itemize}",
      "    \\item Why is this problem important?",
      "    \\item What gap does this work address?",
      "    \\item Key challenges we overcome:",
      "    \\begin{itemize}",
      "      \\item Challenge 1",
      "      \\item Challenge 2",
      "    \\end{itemize}",
      "  \\end{itemize}",
      "\\end{frame}",
      "",
      "\\section{Method}",
      "",
      "\\begin{frame}{Our Approach}",
      "  \\begin{block}{Main Idea}",
      "    We propose a method based on the following key insight...",
      "  \\end{block}",
      "",
      "  The gradient descent update is:",
      "  \\[",
      "    x_{n+1} = x_n - \\alpha \\nabla f(x_n)",
      "  \\]",
      "",
      "  where $\\alpha$ is the learning rate.",
      "\\end{frame}",
      "",
      "\\section{Results}",
      "",
      "\\begin{frame}{Experimental Results}",
      "  Dataset A: Accuracy 94.2\\%, F1 Score 0.941\\\\",
      "  Dataset B: Accuracy 91.7\\%, F1 Score 0.918",
      "\\end{frame}",
      "",
      "\\section{Conclusion}",
      "",
      "\\begin{frame}{Conclusion}",
      "  \\begin{itemize}",
      "    \\item We presented a novel approach to...",
      "    \\item Our method outperforms baselines on X benchmarks",
      "    \\item Future work: extension to larger datasets",
      "  \\end{itemize}",
      "  \\vspace{1.5em}",
      "  \\centering \\Large \\textbf{Thank you! Questions?}",
      "\\end{frame}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "math-assignment",
    icon: "🧮",
    title: "Math Assignment",
    category: "Homework",
    desc: "Problem set template with theorem/proof environments and custom commands.",
    source: [
      "\\documentclass[12pt]{article}",
      "\\usepackage{amsmath,amssymb,amsthm}",
      "\\usepackage{geometry}",
      "\\geometry{margin=2.5cm}",
      "\\usepackage{enumitem}",
      "",
      "% Custom commands",
      "\\newcommand{\\R}{\\mathbb{R}}",
      "\\newcommand{\\N}{\\mathbb{N}}",
      "\\newcommand{\\Z}{\\mathbb{Z}}",
      "\\newcommand{\\eps}{\\varepsilon}",
      "",
      "% Theorem environments",
      "\\newtheorem{theorem}{Theorem}",
      "\\newtheorem{lemma}[theorem]{Lemma}",
      "\\theoremstyle{definition}",
      "\\newtheorem{definition}{Definition}",
      "",
      "\\title{Problem Set 3}",
      "\\author{Your Name}",
      "\\date{Due: \\today}",
      "",
      "\\begin{document}",
      "\\maketitle",
      "",
      "\\section*{Problem 1}",
      "",
      "Prove that every bounded sequence in $\\R^n$ has a convergent subsequence.",
      "",
      "\\textbf{Proof.}",
      "We proceed by induction on $n$.",
      "",
      "\\textbf{Base case} ($n=1$): By the Bolzano-Weierstrass theorem, every bounded sequence",
      "in $\\R$ has a convergent subsequence.",
      "",
      "\\textbf{Inductive step}: Assume the result holds for $\\R^{n-1}$. Let $(\\mathbf{x}_k)$",
      "be a bounded sequence in $\\R^n$. The projection onto the first coordinate is bounded in $\\R$,",
      "so it has a convergent subsequence by the base case. $\\square$",
      "",
      "\\section*{Problem 2}",
      "",
      "Let $f: \\R \\to \\R$ be differentiable. Show that if $|f'(x)| \\leq M$ for all $x$, then:",
      "",
      "\\[",
      "  |f(x) - f(y)| \\leq M|x - y| \\quad \\text{for all } x, y \\in \\R",
      "\\]",
      "",
      "\\textbf{Proof.}",
      "By the Mean Value Theorem, there exists $c$ between $x$ and $y$ such that",
      "$f(x) - f(y) = f'(c)(x-y)$.",
      "Taking absolute values gives $|f(x) - f(y)| \\leq M|x-y|$. $\\square$",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "letter",
    icon: "✉️",
    title: "Cover Letter",
    category: "Career",
    desc: "Professional cover letter for academic or industry job applications.",
    source: [
      "\\documentclass[11pt,a4paper]{article}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage{geometry}",
      "\\geometry{margin=2.5cm}",
      "",
      "\\begin{document}",
      "",
      "\\noindent",
      "\\textbf{Your Name}\\\\",
      "Department, University\\\\",
      "City, Country\\\\",
      "you@example.com",
      "",
      "\\vspace{1em}",
      "\\noindent \\today",
      "",
      "\\vspace{1em}",
      "\\noindent",
      "Hiring Manager\\\\",
      "Company / Department\\\\",
      "City, Country",
      "",
      "\\vspace{1em}",
      "\\noindent Dear Hiring Committee,",
      "",
      "I am writing to apply for the position of [Role] at [Organization].",
      "I am currently a [your status] at [institution], specializing in [your field].",
      "",
      "My research focuses on [describe your research in 1-2 sentences].",
      "I believe my background in [skills/areas] makes me a strong candidate for this position.",
      "",
      "During my time at [previous institution/company], I [achievement 1].",
      "Additionally, I [achievement 2].",
      "These experiences have equipped me with [skills] directly applicable to your team's work.",
      "",
      "I am particularly drawn to [Organization] because [specific reason].",
      "I am confident that I could contribute meaningfully to [specific project or goal].",
      "",
      "I have attached my CV and would welcome the opportunity to discuss further.",
      "",
      "\\vspace{1em}",
      "\\noindent Sincerely,\\\\[2em]",
      "\\noindent \\textbf{Your Name}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "physics",
    icon: "⚛️",
    title: "Physics Lab Report",
    category: "Research",
    desc: "Structured lab report with error analysis, tables, and SI units.",
    source: [
      "\\documentclass[12pt,a4paper]{article}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage{amsmath,amssymb}",
      "\\usepackage{siunitx}",
      "\\usepackage{booktabs}",
      "\\usepackage{geometry}",
      "\\geometry{margin=2.5cm}",
      "",
      "\\title{Lab Report: Measurement of Gravitational Acceleration}",
      "\\author{Student Name \\\\ Partner Name}",
      "\\date{\\today}",
      "",
      "\\begin{document}",
      "\\maketitle",
      "",
      "\\section{Objective}",
      "",
      "Determine the local gravitational acceleration $g$ using a simple pendulum,",
      "and compare the result to the accepted value of",
      "$g = \\SI{9.81}{m/s^2}$.",
      "",
      "\\section{Theory}",
      "",
      "For small oscillations, the period $T$ of a simple pendulum of length $L$ is:",
      "",
      "\\[",
      "  T = 2\\pi\\sqrt{\\frac{L}{g}}",
      "\\]",
      "",
      "Solving for $g$:",
      "",
      "\\[",
      "  g = \\frac{4\\pi^2 L}{T^2}",
      "\\]",
      "",
      "\\section{Data}",
      "",
      "\\begin{table}[h]",
      "\\centering",
      "\\begin{tabular}{ccc}",
      "\\toprule",
      "Trial & Length $L$ (m) & Period $T$ (s) \\\\",
      "\\midrule",
      "1 & 0.500 & 1.421 \\\\",
      "2 & 0.500 & 1.419 \\\\",
      "3 & 0.500 & 1.423 \\\\",
      "\\midrule",
      "Mean & 0.500 & 1.421 \\\\",
      "\\bottomrule",
      "\\end{tabular}",
      "\\caption{Pendulum period measurements at fixed length $L = \\SI{0.500}{m}$.}",
      "\\end{table}",
      "",
      "\\section{Results}",
      "",
      "Using $L = \\SI{0.500}{m}$ and $T = \\SI{1.421}{s}$:",
      "",
      "\\[",
      "  g = \\frac{4\\pi^2 \\times 0.500}{(1.421)^2} = \\SI{9.78}{m/s^2}",
      "\\]",
      "",
      "\\section{Error Analysis}",
      "",
      "The percentage error relative to the accepted value is:",
      "\\[",
      "  \\text{error} = \\frac{|9.78 - 9.81|}{9.81} \\times 100\\% = 0.31\\%",
      "\\]",
      "",
      "\\section{Conclusion}",
      "",
      "The measured value $g = \\SI{9.78}{m/s^2}$ agrees with the accepted value",
      "to within experimental uncertainty. Main sources of error: air resistance,",
      "timing reaction delay, and non-zero amplitude.",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  // ─── ACADEMIC / THESIS ───────────────────────────────────────────────────
  {
    id: "phd-thesis",
    icon: "🎓",
    title: "PhD Thesis",
    category: "Thesis",
    desc: "Full doctoral thesis structure: title page, abstract, ToC, chapters, appendices, and bibliography.",
    source: [
      "\\documentclass[12pt, a4paper, twoside]{report}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage{geometry}",
      "\\geometry{inner=3.5cm, outer=2.5cm, top=2.5cm, bottom=2.5cm}",
      "\\usepackage{setspace}",
      "\\onehalfspacing",
      "\\usepackage{graphicx}",
      "\\usepackage{amsmath, amssymb, amsthm}",
      "\\usepackage[hidelinks]{hyperref}",
      "\\usepackage{booktabs}",
      "\\usepackage{microtype}",
      "\\usepackage{fancyhdr}",
      "\\pagestyle{fancy}",
      "",
      "% Theorem environments",
      "\\newtheorem{theorem}{Theorem}[chapter]",
      "\\newtheorem{lemma}[theorem]{Lemma}",
      "\\newtheorem{proposition}[theorem]{Proposition}",
      "\\theoremstyle{definition}",
      "\\newtheorem{definition}{Definition}[chapter]",
      "",
      "\\begin{document}",
      "",
      "% ── Title page ──────────────────────────────",
      "\\begin{titlepage}",
      "  \\centering",
      "  {\\Large University Name}\\\\[1cm]",
      "  {\\Huge \\textbf{Your Thesis Title}}\\\\[0.5cm]",
      "  {\\large Subtitle if applicable}\\\\[2cm]",
      "  {\\normalsize A thesis submitted in partial fulfillment of\\\\",
      "  the requirements for the degree of}\\\\[0.5cm]",
      "  {\\Large \\textbf{Doctor of Philosophy}}\\\\[0.5cm]",
      "  in\\\\[0.3cm]",
      "  {\\large Department of XYZ}\\\\[2cm]",
      "  {\\normalsize by}\\\\[0.3cm]",
      "  {\\large \\textbf{Your Full Name}}\\\\[3cm]",
      "  Supervisor: Prof. Supervisor Name\\\\[0.5cm]",
      "  {\\today}",
      "\\end{titlepage}",
      "",
      "% ── Front matter ────────────────────────────",
      "\\chapter*{Declaration}",
      "I hereby declare that this thesis is my own original work...",
      "\\newpage",
      "",
      "\\chapter*{Abstract}",
      "\\addcontentsline{toc}{chapter}{Abstract}",
      "Your abstract goes here (300--500 words). Summarize your research question,",
      "methodology, key findings, and contribution to the field.",
      "",
      "\\chapter*{Acknowledgements}",
      "\\addcontentsline{toc}{chapter}{Acknowledgements}",
      "I would like to thank my supervisor, Prof. Name, for invaluable guidance...",
      "",
      "\\tableofcontents",
      "\\listoffigures",
      "\\listoftables",
      "",
      "% ── Chapter 1: Introduction ─────────────────",
      "\\chapter{Introduction}",
      "\\label{chap:intro}",
      "",
      "\\section{Background and Motivation}",
      "Introduce your research area and why it matters. Reference prior work \\cite{smith2023}.",
      "",
      "\\section{Research Questions}",
      "\\begin{enumerate}",
      "  \\item RQ1: How does X affect Y?",
      "  \\item RQ2: Can Z be efficiently computed under condition W?",
      "\\end{enumerate}",
      "",
      "\\section{Contributions}",
      "The main contributions of this thesis are:",
      "\\begin{itemize}",
      "  \\item A novel framework for...",
      "  \\item Theoretical analysis proving...",
      "  \\item Empirical validation on...",
      "\\end{itemize}",
      "",
      "\\section{Thesis Structure}",
      "Chapter~\\ref{chap:review} reviews related work.",
      "Chapter~\\ref{chap:method} describes our methodology.",
      "",
      "% ── Chapter 2: Literature Review ────────────",
      "\\chapter{Literature Review}",
      "\\label{chap:review}",
      "",
      "\\section{Overview}",
      "\\subsection{Prior Work on Topic A}",
      "\\subsection{Prior Work on Topic B}",
      "",
      "% ── Chapter 3: Methodology ──────────────────",
      "\\chapter{Methodology}",
      "\\label{chap:method}",
      "",
      "\\section{Research Design}",
      "",
      "\\section{Mathematical Framework}",
      "Let $\\mathcal{X}$ denote the input space. We define:",
      "\\begin{definition}",
      "  A function $f: \\mathcal{X} \\to \\mathbb{R}$ is \\emph{Lipschitz continuous}",
      "  with constant $L$ if for all $x, y \\in \\mathcal{X}$:",
      "  \\[",
      "    |f(x) - f(y)| \\leq L\\|x - y\\|",
      "  \\]",
      "\\end{definition}",
      "",
      "\\begin{theorem}",
      "  State your main theorem here.",
      "\\end{theorem}",
      "\\begin{proof}",
      "  Proof details here. $\\qed$",
      "\\end{proof}",
      "",
      "% ── Chapter 4: Results ──────────────────────",
      "\\chapter{Results}",
      "\\label{chap:results}",
      "",
      "\\section{Main Findings}",
      "",
      "\\begin{table}[ht]",
      "  \\centering",
      "  \\caption{Comparison of methods on benchmark datasets.}",
      "  \\begin{tabular}{lccc}",
      "    \\toprule",
      "    Method & Dataset A & Dataset B & Runtime (s) \\\\",
      "    \\midrule",
      "    Baseline & 0.75 & 0.71 & 12.3 \\\\",
      "    Method X & 0.84 & 0.82 & 15.1 \\\\",
      "    Ours & \\textbf{0.92} & \\textbf{0.89} & 18.4 \\\\",
      "    \\bottomrule",
      "  \\end{tabular}",
      "  \\label{tab:results}",
      "\\end{table}",
      "",
      "% ── Chapter 5: Discussion ───────────────────",
      "\\chapter{Discussion}",
      "\\label{chap:discussion}",
      "",
      "\\section{Interpretation}",
      "\\section{Limitations}",
      "\\section{Future Work}",
      "",
      "% ── Chapter 6: Conclusion ───────────────────",
      "\\chapter{Conclusion}",
      "\\label{chap:conclusion}",
      "",
      "\\section{Summary of Contributions}",
      "\\section{Future Directions}",
      "",
      "% ── Appendices ──────────────────────────────",
      "\\appendix",
      "\\chapter{Supplementary Proofs}",
      "\\chapter{Dataset Details}",
      "",
      "% ── Bibliography ────────────────────────────",
      "\\begin{thebibliography}{9}",
      "\\bibitem{smith2023} Smith, J. (2023). \\textit{Foundational paper}. Nature, 610, 1--8.",
      "\\end{thebibliography}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "masters-thesis",
    icon: "📚",
    title: "Master's Thesis",
    category: "Thesis",
    desc: "Streamlined thesis template for MSc/MEng — cleaner than PhD, still professional.",
    source: [
      "\\documentclass[12pt, a4paper]{report}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage{geometry}",
      "\\geometry{margin=2.5cm}",
      "\\usepackage{setspace}",
      "\\onehalfspacing",
      "\\usepackage{amsmath, amssymb}",
      "\\usepackage[hidelinks]{hyperref}",
      "\\usepackage{graphicx}",
      "\\usepackage{booktabs}",
      "",
      "\\begin{document}",
      "",
      "% ── Title page ──",
      "\\begin{titlepage}",
      "  \\centering",
      "  \\vspace*{2cm}",
      "  {\\large University Name}\\\\[0.5cm]",
      "  {\\large Department of XYZ}\\\\[2cm]",
      "  {\\Huge \\textbf{Your Thesis Title}}\\\\[1cm]",
      "  {\\large \\textit{Submitted in partial fulfillment of the}}\\\\",
      "  {\\large \\textit{requirements for the degree of}}\\\\[0.5cm]",
      "  {\\Large Master of Science}\\\\[2cm]",
      "  {\\large By: \\textbf{Your Name}}\\\\[0.5cm]",
      "  {\\large Supervisor: Prof. Name}\\\\[2cm]",
      "  {\\today}",
      "\\end{titlepage}",
      "",
      "\\chapter*{Abstract}",
      "\\addcontentsline{toc}{chapter}{Abstract}",
      "Write a concise summary of your thesis (200--400 words).",
      "",
      "\\tableofcontents",
      "",
      "\\chapter{Introduction}",
      "\\section{Problem Statement}",
      "\\section{Objectives}",
      "\\section{Report Structure}",
      "",
      "\\chapter{Background}",
      "\\section{Related Work}",
      "\\section{Theoretical Background}",
      "",
      "Some key equations:",
      "\\[",
      "  \\nabla^2 \\phi = -\\frac{\\rho}{\\varepsilon_0}",
      "\\]",
      "",
      "\\chapter{Approach}",
      "\\section{Design}",
      "\\section{Implementation}",
      "",
      "\\chapter{Evaluation}",
      "\\section{Experimental Setup}",
      "",
      "\\begin{table}[ht]",
      "  \\centering",
      "  \\caption{Results summary.}",
      "  \\begin{tabular}{lcc}",
      "    \\toprule",
      "    Metric & Baseline & Ours \\\\",
      "    \\midrule",
      "    Accuracy & 82\\% & \\textbf{91\\%} \\\\",
      "    Latency (ms) & 45 & 38 \\\\",
      "    \\bottomrule",
      "  \\end{tabular}",
      "\\end{table}",
      "",
      "\\chapter{Conclusion}",
      "\\section{Summary}",
      "\\section{Future Work}",
      "",
      "\\appendix",
      "\\chapter{Additional Results}",
      "",
      "\\begin{thebibliography}{9}",
      "\\bibitem{ref1} Author, A. (2022). \\textit{Paper title}. Conference, pp. 1--10.",
      "\\end{thebibliography}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "ieee-paper",
    icon: "📡",
    title: "IEEE Conference Paper",
    category: "Research",
    desc: "Two-column IEEE format ready for submission to conferences (IEEEtran class).",
    source: [
      "\\documentclass[conference]{IEEEtran}",
      "\\usepackage{amsmath,amssymb}",
      "\\usepackage{graphicx}",
      "\\usepackage{cite}",
      "\\usepackage{url}",
      "\\usepackage[hidelinks]{hyperref}",
      "",
      "\\begin{document}",
      "",
      "\\title{Title of Your IEEE Paper}",
      "",
      "\\author{",
      "  \\IEEEauthorblockN{First Author}",
      "  \\IEEEauthorblockA{Department of XYZ\\\\",
      "  University, City, Country\\\\",
      "  first.author@university.edu}",
      "  \\and",
      "  \\IEEEauthorblockN{Second Author}",
      "  \\IEEEauthorblockA{Department of ABC\\\\",
      "  University, City, Country\\\\",
      "  second.author@university.edu}",
      "}",
      "",
      "\\maketitle",
      "",
      "\\begin{abstract}",
      "This paper presents... (150 words max for IEEE). Summarize the problem,",
      "your approach, and key results clearly and concisely.",
      "\\end{abstract}",
      "",
      "\\begin{IEEEkeywords}",
      "machine learning, optimization, deep learning, neural networks",
      "\\end{IEEEkeywords}",
      "",
      "\\section{Introduction}",
      "Introduce the problem and your contributions.",
      "Recent work \\cite{author2023} has shown that...",
      "",
      "\\section{Related Work}",
      "Discuss related approaches and their limitations.",
      "",
      "\\section{Proposed Method}",
      "\\subsection{Problem Formulation}",
      "Let $\\mathbf{x} \\in \\mathbb{R}^d$ denote the input. We optimize:",
      "\\[",
      "  \\min_{\\theta} \\mathcal{L}(\\theta) = \\frac{1}{n}\\sum_{i=1}^{n}",
      "  \\ell(f_\\theta(\\mathbf{x}_i), y_i)",
      "\\]",
      "",
      "\\subsection{Algorithm}",
      "Describe your algorithm here.",
      "",
      "\\section{Experiments}",
      "\\subsection{Setup}",
      "We evaluate on [datasets]. All experiments use [hardware].",
      "",
      "\\subsection{Results}",
      "Table \\ref{tab:results} shows that our method achieves...",
      "",
      "\\begin{table}[ht]",
      "  \\centering",
      "  \\caption{Performance comparison.}",
      "  \\begin{tabular}{lcc}",
      "    \\hline",
      "    Method & Acc. (\\%) & FLOPs \\\\",
      "    \\hline",
      "    Baseline~\\cite{author2023} & 88.2 & 2.3G \\\\",
      "    \\textbf{Ours} & \\textbf{93.1} & 2.5G \\\\",
      "    \\hline",
      "  \\end{tabular}",
      "  \\label{tab:results}",
      "\\end{table}",
      "",
      "\\section{Conclusion}",
      "We proposed a method that achieves state-of-the-art results on [task].",
      "",
      "\\begin{thebibliography}{1}",
      "\\bibitem{author2023}",
      "A.~Author, B.~Author, ``Title of referenced paper,''",
      "\\textit{IEEE Trans. Pattern Anal.}, vol.~45, no.~1, pp.~1--10, 2023.",
      "\\end{thebibliography}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "research-proposal",
    icon: "💡",
    title: "Research Proposal",
    category: "Thesis",
    desc: "Structured research proposal for PhD applications, grants, or funding bodies.",
    source: [
      "\\documentclass[12pt, a4paper]{article}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage{geometry}",
      "\\geometry{margin=2.5cm}",
      "\\usepackage{setspace}",
      "\\onehalfspacing",
      "\\usepackage{amsmath}",
      "\\usepackage[hidelinks]{hyperref}",
      "\\usepackage{titlesec}",
      "",
      "\\title{Research Proposal \\\\[0.3em] {\\large Title of Your Proposed Research}}",
      "\\author{Candidate Name\\\\",
      "  {\\small Proposed Supervisor: Prof. Name}\\\\",
      "  {\\small Institution, Department}}",
      "\\date{\\today}",
      "",
      "\\begin{document}",
      "\\maketitle",
      "",
      "\\section{Research Overview}",
      "",
      "\\subsection{Background}",
      "Briefly introduce the research area and its importance.",
      "",
      "\\subsection{Problem Statement}",
      "Clearly state the gap in knowledge that your research will address.",
      "",
      "\\subsection{Research Questions}",
      "\\begin{enumerate}",
      "  \\item Primary: How does X affect Y in context Z?",
      "  \\item Secondary: Can method A scale to settings B?",
      "\\end{enumerate}",
      "",
      "\\section{Literature Review}",
      "",
      "Summarize key existing work and explain how your research builds on it.",
      "Key papers: \\cite{smith2023, jones2022}.",
      "",
      "\\section{Methodology}",
      "",
      "\\subsection{Research Design}",
      "Describe your overall approach (qualitative/quantitative/mixed).",
      "",
      "\\subsection{Methods}",
      "\\begin{itemize}",
      "  \\item Data collection: ...",
      "  \\item Analysis: ...",
      "  \\item Validation: ...",
      "\\end{itemize}",
      "",
      "\\subsection{Mathematical Approach}",
      "Describe any key equations or models if applicable:",
      "\\[",
      "  \\hat{y} = f(\\mathbf{x}; \\theta) + \\varepsilon, \\quad \\varepsilon \\sim \\mathcal{N}(0, \\sigma^2)",
      "\\]",
      "",
      "\\section{Timeline}",
      "",
      "\\begin{tabular}{ll}",
      "  Months 1--6   & Literature review, data collection \\\\",
      "  Months 7--18  & Model development and experiments \\\\",
      "  Months 19--30 & Analysis, writing, dissemination \\\\",
      "  Months 31--36 & Thesis writing and submission \\\\",
      "\\end{tabular}",
      "",
      "\\section{Expected Contributions}",
      "",
      "This research will contribute:",
      "\\begin{itemize}",
      "  \\item A new theoretical framework for...",
      "  \\item An empirical study demonstrating...",
      "  \\item Open-source tools enabling...",
      "\\end{itemize}",
      "",
      "\\section{Budget Justification}",
      "If applicable, justify funding requirements here.",
      "",
      "\\begin{thebibliography}{9}",
      "\\bibitem{smith2023} Smith, J. (2023). \\textit{Key paper}. Nature, 610, 1--8.",
      "\\bibitem{jones2022} Jones, A. (2022). \\textit{Related work}. ICML, pp. 1--10.",
      "\\end{thebibliography}",
      "",
      "\\end{document}",
    ].join("\n"),
  },

  // ─── CENTRALE MARSEILLE / GRANDE ÉCOLE ──────────────────────────────────
  {
    id: "ec-report",
    icon: "🏛️",
    title: "Centrale Méditerranée — Rapport de projet",
    category: "Grande École",
    desc: "Rapport académique avec en-tête Centrale Méditerranée, page de titre, sections bilingues, et mise en forme aux couleurs de l'école.",
    source: [
      "\\documentclass[12pt, a4paper]{report}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage[french,english]{babel}",
      "\\usepackage{geometry}",
      "\\geometry{top=2.5cm, bottom=2.5cm, left=2.8cm, right=2.5cm}",
      "\\usepackage{graphicx}",
      "\\usepackage{amsmath, amssymb}",
      "\\usepackage[hidelinks]{hyperref}",
      "\\usepackage{setspace}",
      "\\onehalfspacing",
      "\\usepackage{xcolor}",
      "\\usepackage{booktabs}",
      "\\usepackage{fancyhdr}",
      "",
      "% ── Centrale Méditerranée brand colours ──",
      "\\definecolor{ecGray}{RGB}{95, 106, 122}",
      "\\definecolor{ecBlue}{RGB}{0,  56, 168}",
      "",
      "% ── Running headers ──────────────────────",
      "\\pagestyle{fancy}",
      "\\fancyhf{}",
      "\\rhead{\\textcolor{ecGray}{\\small Centrale Méditerranée}}",
      "\\lhead{\\textcolor{ecGray}{\\small Rapport de projet}}",
      "\\cfoot{\\thepage}",
      "\\renewcommand{\\headrulewidth}{0.4pt}",
      "",
      "\\begin{document}",
      "",
      "% ══════════════════════════════════════════",
      "% PAGE DE TITRE",
      "% ══════════════════════════════════════════",
      "\\begin{titlepage}",
      "  \\centering",
      "",
      "  % School header",
      "  % Uncomment the next line and add your logo file:",
      "  % \\includegraphics[width=5cm]{centrale-med-logo}\\\\[0.4cm]",
      "  {\\color{ecGray}\\rule{\\linewidth}{2.5pt}}\\\\[0.2cm]",
      "  {\\color{ecBlue}\\fontsize{22}{26}\\selectfont\\textbf{Centrale}\\;{\\color{ecGray}Méditerranée}}\\\\[0.1cm]",
      "  {\\color{ecGray}\\small\\textit{École Centrale de Marseille · Aix-Marseille Université}}\\\\[0.1cm]",
      "  {\\color{ecGray}\\rule{\\linewidth}{0.5pt}}",
      "",
      "  \\vspace{2.5cm}",
      "  {\\LARGE\\bfseries Titre du rapport / Projet de fin d'études}\\\\[0.5cm]",
      "  {\\large\\color{ecGray} Sous-titre ou nature du document}",
      "  \\vspace{2.5cm}",
      "",
      "  \\begin{tabular}{r l}",
      "    \\textbf{Auteur}       & Prénom \\textsc{Nom} \\\\[4pt]",
      "    \\textbf{Promotion}    & 2022--2025 \\\\[4pt]",
      "    \\textbf{Département}  & Informatique \\& Systèmes \\\\[4pt]",
      "    \\textbf{Encadrant}    & Prof.~Prénom \\textsc{Nom} \\\\[4pt]",
      "    \\textbf{Partenaire}   & Nom de l'entreprise / laboratoire \\\\[4pt]",
      "    \\textbf{Période}      & Janvier -- Juin 2025 \\\\",
      "  \\end{tabular}",
      "",
      "  \\vfill",
      "  {\\color{ecGray}\\rule{\\linewidth}{2.5pt}}\\\\[0.25cm]",
      "  {\\small\\color{ecGray}\\today}",
      "\\end{titlepage}",
      "",
      "% ── Front matter ────────────────────────────────────────────────────",
      "\\chapter*{Remerciements}",
      "\\addcontentsline{toc}{chapter}{Remerciements}",
      "Je tiens à remercier mon encadrant, Prof.~Nom, pour son soutien tout au long de ce projet, ainsi que l'équipe de [entreprise/laboratoire] pour leur accueil.",
      "",
      "\\chapter*{Résumé}",
      "\\addcontentsline{toc}{chapter}{Résumé}",
      "\\selectlanguage{french}",
      "Ce rapport présente les travaux réalisés dans le cadre de [contexte]. L'objectif principal est de [objectif]. Les principaux résultats obtenus sont [résultats].",
      "",
      "\\textbf{Mots-clés :} mot1, mot2, mot3.",
      "",
      "\\selectlanguage{english}",
      "\\chapter*{Abstract}",
      "\\addcontentsline{toc}{chapter}{Abstract}",
      "This report presents the work carried out in the context of [context]. The main objective is [objective]. Key results include [results].",
      "",
      "\\textbf{Keywords:} keyword1, keyword2, keyword3.",
      "",
      "\\tableofcontents",
      "\\listoffigures",
      "\\listoftables",
      "",
      "% ── Chapter 1: Introduction ─────────────────────────────────────────",
      "\\chapter{Introduction}",
      "",
      "\\section{Contexte et motivation}",
      "Présenter le cadre général du projet. Expliquer pourquoi ce travail est important.",
      "",
      "\\section{Problématique}",
      "Définir clairement la question ou le problème central que ce rapport adresse.",
      "",
      "\\section{Objectifs}",
      "\\begin{enumerate}",
      "  \\item Objectif principal : ...",
      "  \\item Objectif secondaire 1 : ...",
      "  \\item Objectif secondaire 2 : ...",
      "\\end{enumerate}",
      "",
      "\\section{Plan du rapport}",
      "Le chapitre~2 présente l'état de l'art. Le chapitre~3 décrit la méthodologie. Le chapitre~4 présente et analyse les résultats. Le chapitre~5 conclut et propose des perspectives.",
      "",
      "% ── Chapter 2: État de l'art ────────────────────────────────────────",
      "\\chapter{État de l'art}",
      "",
      "\\section{Contexte théorique}",
      "Références aux travaux existants. Par exemple, \\cite{auteur2023}.",
      "",
      "\\section{Comparaison des approches}",
      "\\begin{table}[ht]",
      "  \\centering",
      "  \\caption{Comparaison des méthodes existantes.}",
      "  \\begin{tabular}{lccc}",
      "    \\toprule",
      "    Méthode & Précision & Temps & Complexité \\\\",
      "    \\midrule",
      "    Méthode A & 88\\% & 12\\,ms & $O(n)$ \\\\",
      "    Méthode B & 91\\% & 45\\,ms & $O(n^2)$ \\\\",
      "    Notre approche & \\textbf{94\\%} & \\textbf{18\\,ms} & $O(n\\log n)$ \\\\",
      "    \\bottomrule",
      "  \\end{tabular}",
      "  \\label{tab:sota}",
      "\\end{table}",
      "",
      "% ── Chapter 3: Méthodologie ─────────────────────────────────────────",
      "\\chapter{Méthodologie}",
      "",
      "\\section{Architecture proposée}",
      "Description de la solution. Inclure une figure si possible.",
      "",
      "\\section{Formulation mathématique}",
      "La fonction objectif à minimiser est :",
      "\\[",
      "  \\mathcal{L}(\\theta) = \\frac{1}{n}\\sum_{i=1}^{n}",
      "  \\ell\\!\\left(f_\\theta(\\mathbf{x}_i),\\, y_i\\right) + \\lambda\\|\\theta\\|_2^2",
      "\\]",
      "",
      "où $\\lambda > 0$ est le paramètre de régularisation.",
      "",
      "% ── Chapter 4: Résultats ────────────────────────────────────────────",
      "\\chapter{Résultats et analyse}",
      "",
      "\\section{Protocole expérimental}",
      "Décrire les données, l'environnement matériel (CPU/GPU) et les métriques d'évaluation.",
      "",
      "\\section{Résultats principaux}",
      "Commentez les résultats du tableau~\\ref{tab:sota}.",
      "",
      "\\section{Discussion}",
      "Analyser les forces et limites de l'approche.",
      "",
      "% ── Chapter 5: Conclusion ───────────────────────────────────────────",
      "\\chapter{Conclusion et perspectives}",
      "",
      "\\section{Bilan}",
      "Résumer les contributions du rapport.",
      "",
      "\\section{Perspectives}",
      "\\begin{itemize}",
      "  \\item Extension à des jeux de données plus larges",
      "  \\item Intégration dans un système de production",
      "  \\item Publication des résultats",
      "\\end{itemize}",
      "",
      "\\begin{thebibliography}{9}",
      "\\bibitem{auteur2023} Auteur, P. (2023). \\textit{Titre de l'article}. Journal Name, 42(1), 1--10.",
      "\\end{thebibliography}",
      "",
      "\\appendix",
      "\\chapter{Données supplémentaires}",
      "Ajouter ici les tableaux, courbes, ou preuves secondaires.",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "ec-internship",
    icon: "🏢",
    title: "Centrale Marseille — Rapport de stage",
    category: "Grande École",
    desc: "Rapport de stage officiel : page de titre bilingue, clause de confidentialité, structure complète entreprise + école.",
    source: [
      "\\documentclass[12pt, a4paper]{report}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage[french]{babel}",
      "\\usepackage{geometry}",
      "\\geometry{top=2.5cm, bottom=2.5cm, left=3cm, right=2.5cm}",
      "\\usepackage{graphicx}",
      "\\usepackage{amsmath, amssymb}",
      "\\usepackage[hidelinks]{hyperref}",
      "\\usepackage{setspace}",
      "\\onehalfspacing",
      "\\usepackage{xcolor}",
      "\\usepackage{booktabs}",
      "\\usepackage{fancyhdr}",
      "",
      "\\definecolor{ecGray}{RGB}{95, 106, 122}",
      "\\definecolor{ecBlue}{RGB}{0,  56, 168}",
      "",
      "\\pagestyle{fancy}",
      "\\fancyhf{}",
      "\\rhead{\\textcolor{ecGray}{\\small Centrale Marseille}}",
      "\\lhead{\\textcolor{ecGray}{\\small Rapport de stage}}",
      "\\cfoot{\\thepage}",
      "",
      "\\begin{document}",
      "",
      "% ══════════════════════════════════════════",
      "% PAGE DE TITRE",
      "% ══════════════════════════════════════════",
      "\\begin{titlepage}",
      "  \\centering",
      "",
      "  % Logos côte à côte : école + entreprise",
      "  % \\includegraphics[height=2cm]{centrale-marseille-logo}",
      "  % \\hfill",
      "  % \\includegraphics[height=2cm]{company-logo}",
      "",
      "  {\\color{ecGray}\\rule{\\linewidth}{2.5pt}}\\\\[0.15cm]",
      "  \\begin{minipage}{0.5\\linewidth}\\centering",
      "    {\\color{ecBlue}\\large\\textbf{Centrale Marseille}}\\\\",
      "    {\\color{ecGray}\\small École Centrale de Marseille}",
      "  \\end{minipage}",
      "  \\hfill",
      "  \\begin{minipage}{0.4\\linewidth}\\centering",
      "    {\\color{ecGray}\\large\\textbf{Entreprise / Laboratoire}}\\\\",
      "    {\\color{ecGray}\\small Département ou Service}",
      "  \\end{minipage}\\\\[0.15cm]",
      "  {\\color{ecGray}\\rule{\\linewidth}{0.5pt}}",
      "",
      "  \\vspace{2cm}",
      "  {\\small\\color{ecGray}\\textit{Rapport de stage de 1\\textsuperscript{re} / 2\\textsuperscript{e} / 3\\textsuperscript{e} année}}\\\\[0.4cm]",
      "  {\\LARGE\\bfseries Titre du stage}\\\\[0.4cm]",
      "  {\\large\\color{ecGray} Sous-département ou axe de recherche}",
      "",
      "  \\vspace{2cm}",
      "  \\begin{tabular}{r l}",
      "    \\textbf{Stagiaire}         & Prénom \\textsc{Nom}, promotion 2022--2025 \\\\[4pt]",
      "    \\textbf{Tuteur entreprise} & M./Mme Prénom \\textsc{Nom}, poste \\\\[4pt]",
      "    \\textbf{Tuteur école}      & Prof.~Prénom \\textsc{Nom} \\\\[4pt]",
      "    \\textbf{Lieu}             & Ville, Pays \\\\[4pt]",
      "    \\textbf{Durée}            & 3 mois — du 1\\textsuperscript{er} avril au 30 juin 2025 \\\\",
      "  \\end{tabular}",
      "",
      "  \\vfill",
      "  {\\color{ecGray}\\rule{\\linewidth}{2.5pt}}\\\\[0.2cm]",
      "  {\\small\\color{ecGray} Rapport confidentiel — diffusion restreinte}",
      "\\end{titlepage}",
      "",
      "% ── Clause de confidentialité ───────────────────────────────────────",
      "\\thispagestyle{empty}",
      "\\vspace*{3cm}",
      "{\\large\\bfseries\\color{ecBlue} Clause de confidentialité}",
      "",
      "\\medskip",
      "Ce rapport a été réalisé dans le cadre d'un stage effectué du [date début] au [date fin] au sein de [Entreprise].",
      "À la demande de [Entreprise / l'auteur], ce document est confidentiel.",
      "Sa communication à des tiers sans l'autorisation écrite préalable de [Entreprise] est interdite.",
      "Les informations contenues dans ce rapport ne doivent pas être utilisées à des fins autres que l'évaluation académique.",
      "",
      "\\medskip",
      "Fait à [Ville], le \\today.",
      "\\newpage",
      "",
      "% ── Résumé ──────────────────────────────────────────────────────────",
      "\\chapter*{Résumé}",
      "\\addcontentsline{toc}{chapter}{Résumé}",
      "Résumé du stage en 200--300 mots : contexte, missions, résultats, apports personnels.",
      "",
      "\\textbf{Mots-clés :} mot-clé1, mot-clé2, mot-clé3.",
      "",
      "\\chapter*{Remerciements}",
      "\\addcontentsline{toc}{chapter}{Remerciements}",
      "Je remercie [tuteur entreprise] pour son encadrement, [tuteur école] pour ses conseils, et l'équipe de [Entreprise] pour son accueil.",
      "",
      "\\tableofcontents",
      "",
      "% ── Introduction ────────────────────────────────────────────────────",
      "\\chapter{Introduction}",
      "",
      "\\section{Présentation de l'entreprise}",
      "Décrire l'entreprise : secteur, taille, activités, position sur le marché.",
      "",
      "\\section{Présentation du service d'accueil}",
      "Décrire le département ou l'équipe dans lequel s'est déroulé le stage.",
      "",
      "\\section{Contexte et objectifs du stage}",
      "Expliquer le contexte du stage et les objectifs fixés en début de mission.",
      "",
      "% ── Missions ────────────────────────────────────────────────────────",
      "\\chapter{Missions réalisées}",
      "",
      "\\section{Mission 1 : [Titre]}",
      "\\subsection{Contexte}",
      "\\subsection{Travail effectué}",
      "\\subsection{Résultats}",
      "",
      "\\section{Mission 2 : [Titre]}",
      "\\subsection{Contexte}",
      "\\subsection{Approche technique}",
      "Si pertinent, inclure une équation ou un schéma :",
      "\\[",
      "  \\hat{y} = \\mathbf{w}^\\top \\mathbf{x} + b",
      "\\]",
      "\\subsection{Résultats}",
      "",
      "% ── Analyse et apports ──────────────────────────────────────────────",
      "\\chapter{Analyse critique et apports}",
      "",
      "\\section{Apports professionnels}",
      "Compétences techniques, méthodologiques et organisationnelles acquises.",
      "",
      "\\section{Apports personnels}",
      "Gestion du temps, travail en équipe, communication en entreprise.",
      "",
      "\\section{Bilan et perspectives}",
      "Ce que ce stage m'a apporté et en quoi il éclaire mon projet professionnel.",
      "",
      "% ── Conclusion ──────────────────────────────────────────────────────",
      "\\chapter{Conclusion}",
      "Bilan synthétique du stage et ouverture sur la suite du parcours.",
      "",
      "\\begin{thebibliography}{9}",
      "\\bibitem{ref1} Auteur, A. (2024). \\textit{Titre}. Source.",
      "\\end{thebibliography}",
      "",
      "\\appendix",
      "\\chapter{Glossaire technique}",
      "\\chapter{Documents de référence}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "amse-paper",
    icon: "📈",
    title: "AMSE — Working Paper / Research Note",
    category: "Grande École",
    desc: "Format papier de recherche pour Aix-Marseille School of Economics : JEL codes, abstract structuré, bibliographie économique.",
    source: [
      "\\documentclass[12pt, a4paper]{article}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage[english]{babel}",
      "\\usepackage{geometry}",
      "\\geometry{top=3cm, bottom=3cm, left=3cm, right=3cm}",
      "\\usepackage{amsmath, amssymb, amsthm}",
      "\\usepackage[hidelinks]{hyperref}",
      "\\usepackage{setspace}",
      "\\onehalfspacing",
      "\\usepackage{xcolor}",
      "\\usepackage{booktabs}",
      "\\usepackage{natbib}",
      "\\usepackage{microtype}",
      "",
      "% ── AMSE brand colours ───────────────────────",
      "\\definecolor{amseOrange}{RGB}{245, 166, 35}",
      "\\definecolor{amseBlue}{RGB}{0,  62, 160}",
      "",
      "% ── Theorem environments ─────────────────────",
      "\\newtheorem{theorem}{Theorem}",
      "\\newtheorem{proposition}[theorem]{Proposition}",
      "\\newtheorem{lemma}[theorem]{Lemma}",
      "\\newtheorem{corollary}[theorem]{Corollary}",
      "\\theoremstyle{definition}",
      "\\newtheorem{assumption}{Assumption}",
      "\\newtheorem{definition}{Definition}",
      "\\theoremstyle{remark}",
      "\\newtheorem{remark}{Remark}",
      "",
      "% ── Custom commands ──────────────────────────",
      "\\newcommand{\\E}{\\mathbb{E}}",
      "\\newcommand{\\R}{\\mathbb{R}}",
      "\\newcommand{\\N}{\\mathbb{N}}",
      "\\newcommand{\\eps}{\\varepsilon}",
      "\\newcommand{\\Var}{\\operatorname{Var}}",
      "\\newcommand{\\Cov}{\\operatorname{Cov}}",
      "\\newcommand{\\plim}{\\operatorname{plim}}",
      "",
      "\\begin{document}",
      "",
      "% ── AMSE header ─────────────────────────────────────────────────────",
      "\\noindent",
      "{\\color{amseBlue}\\rule{\\linewidth}{2pt}}\\\\[0.2cm]",
      "\\begin{minipage}{0.72\\linewidth}",
      "  {\\color{amseBlue}\\large\\textbf{Working Paper} \\color{amseOrange}\\textbf{|} \\color{amseBlue}\\large Aix-Marseille School of Economics}\\\\",
      "  {\\small\\color{gray} Aix-Marseille Université · CNRS · EHESS · Centrale Méditerranée}",
      "\\end{minipage}",
      "\\hfill",
      "\\begin{minipage}{0.24\\linewidth}\\raggedleft",
      "  % \\includegraphics[width=3cm]{amse-logo}",
      "  {\\color{amseOrange}\\textbf{AMSE}}\\\\",
      "  {\\small\\color{gray} WP \\#2025-XX}",
      "\\end{minipage}\\\\[0.2cm]",
      "{\\color{amseBlue}\\rule{\\linewidth}{0.4pt}}",
      "",
      "\\vspace{1.5cm}",
      "",
      "% ── Title block ─────────────────────────────────────────────────────",
      "\\begin{center}",
      "{\\LARGE\\bfseries Title of Your Working Paper}\\\\[0.8cm]",
      "",
      "\\begin{tabular}{cc}",
      "  \\textbf{First Author} & \\textbf{Second Author} \\\\",
      "  \\small Aix-Marseille University & \\small CNRS \\& AMSE \\\\",
      "  \\small \\href{mailto:first@univ-amu.fr}{first@univ-amu.fr} &",
      "  \\small \\href{mailto:second@cnrs.fr}{second@cnrs.fr} \\\\",
      "\\end{tabular}",
      "\\end{center}",
      "",
      "\\vspace{0.5cm}",
      "\\noindent\\small\\textit{This version:} \\today",
      "",
      "\\vspace{1.2cm}",
      "",
      "% ── Abstract ────────────────────────────────────────────────────────",
      "\\begin{abstract}",
      "\\noindent",
      "We study [research question]. Using [methodology/data], we show that [main finding].",
      "This result is robust to [robustness checks]. Our findings contribute to the literature on",
      "[literature stream] by [contribution]. We discuss implications for [policy/theory].",
      "",
      "\\medskip",
      "\\noindent\\textbf{Keywords:} keyword1, keyword2, keyword3, keyword4.",
      "",
      "\\medskip",
      "\\noindent\\textbf{JEL Classification:} C14, D72, E32.",
      "\\end{abstract}",
      "",
      "\\newpage",
      "",
      "% ── 1. Introduction ─────────────────────────────────────────────────",
      "\\section{Introduction}",
      "",
      "Start with the economic question and its importance.",
      "\\citet{smith2023} shows that... Our paper differs in that...",
      "",
      "\\paragraph{Related literature.}",
      "This paper relates to three strands of the literature.",
      "First, \\citet{jones2022}... Second, \\citet{lee2021}... Third,...",
      "",
      "\\paragraph{Contribution.}",
      "Our main contributions are: (i)~a novel identification strategy; (ii)~a dataset covering [scope]; and (iii)~policy implications for [domain].",
      "",
      "\\paragraph{Structure.}",
      "Section~2 describes the model. Section~3 presents the data. Section~4 contains the main results. Section~5 concludes.",
      "",
      "% ── 2. Model ────────────────────────────────────────────────────────",
      "\\section{Model}",
      "",
      "\\subsection{Environment}",
      "Time is discrete. There is a continuum of agents $i \\in [0,1]$.",
      "Agent $i$'s utility is:",
      "\\[",
      "  U_i = \\E_0\\!\\left[\\sum_{t=0}^\\infty \\beta^t u(c_{it}, l_{it})\\right]",
      "\\]",
      "where $\\beta \\in (0,1)$ is the discount factor, $c_{it}$ is consumption, and $l_{it}$ is leisure.",
      "",
      "\\begin{assumption}\\label{ass:utility}",
      "  The utility function $u: \\R_+^2 \\to \\R$ is strictly concave and twice continuously differentiable.",
      "\\end{assumption}",
      "",
      "\\subsection{Equilibrium}",
      "",
      "\\begin{proposition}\\label{prop:exist}",
      "  Under Assumption~\\ref{ass:utility}, a competitive equilibrium exists and is unique.",
      "\\end{proposition}",
      "\\begin{proof}",
      "  Apply Kakutani's fixed-point theorem to the excess demand correspondence. $\\square$",
      "\\end{proof}",
      "",
      "% ── 3. Data ─────────────────────────────────────────────────────────",
      "\\section{Data and Identification Strategy}",
      "",
      "\\subsection{Data sources}",
      "We use [dataset] covering [time period] and [geographical scope].",
      "",
      "\\subsection{Descriptive statistics}",
      "\\begin{table}[ht]",
      "  \\centering",
      "  \\caption{Summary statistics.}",
      "  \\begin{tabular}{lcccc}",
      "    \\toprule",
      "    Variable & Mean & Std.\\ Dev. & Min & Max \\\\",
      "    \\midrule",
      "    Variable 1 & 4.23 & 1.12 & 1.00 & 8.50 \\\\",
      "    Variable 2 & 0.58 & 0.21 & 0.10 & 0.95 \\\\",
      "    Outcome    & 2.31 & 0.84 & 0.00 & 6.12 \\\\",
      "    \\bottomrule",
      "  \\end{tabular}",
      "  \\label{tab:stats}",
      "\\end{table}",
      "",
      "\\subsection{Identification}",
      "We exploit [natural experiment / instrumental variable] as an exogenous source of variation in [endogenous variable].",
      "The first-stage equation is:",
      "\\[",
      "  x_{it} = \\alpha_0 + \\alpha_1 z_{it} + \\mathbf{X}_{it}'\\boldsymbol{\\gamma} + \\mu_i + \\lambda_t + \\eps_{it}",
      "\\]",
      "",
      "% ── 4. Results ──────────────────────────────────────────────────────",
      "\\section{Results}",
      "",
      "\\subsection{Main results}",
      "Table~\\ref{tab:main} presents our main results.",
      "",
      "\\begin{table}[ht]",
      "  \\centering",
      "  \\caption{Main regression results.}",
      "  \\begin{tabular}{lcc}",
      "    \\toprule",
      "    & (1) OLS & (2) IV \\\\",
      "    \\midrule",
      "    Treatment effect & $0.32^{***}$ & $0.47^{***}$ \\\\",
      "    & $(0.08)$ & $(0.12)$ \\\\",
      "    Controls & \\checkmark & \\checkmark \\\\",
      "    Fixed effects & Yes & Yes \\\\",
      "    Observations & 12\\,450 & 12\\,450 \\\\",
      "    \\bottomrule",
      "  \\end{tabular}",
      "  \\\\[4pt]",
      "  \\small\\textit{Note:} Standard errors clustered at region level in parentheses.",
      "  $^{***}$ p$<$0.01, $^{**}$ p$<$0.05, $^{*}$ p$<$0.1.",
      "  \\label{tab:main}",
      "\\end{table}",
      "",
      "\\subsection{Robustness}",
      "Our results are robust to [alternative specification] and [placebo test].",
      "",
      "% ── 5. Conclusion ───────────────────────────────────────────────────",
      "\\section{Conclusion}",
      "We document that [main finding]. This has implications for [policy/literature].",
      "Future work should address [limitation] by [approach].",
      "",
      "% ── References ──────────────────────────────────────────────────────",
      "\\bibliographystyle{aer}   % American Economic Review style",
      "% \\bibliography{references}  % Uncomment and create references.bib",
      "",
      "\\begin{thebibliography}{9}",
      "\\bibitem[Jones(2022)]{jones2022}",
      "Jones, A., and B.~Smith (2022).",
      "``\\href{https://doi.org/10.xxxx/xxxx}{Title of Paper.}''",
      "\\textit{American Economic Review}, 112(4), 1234--1267.",
      "\\bibitem[Lee(2021)]{lee2021}",
      "Lee, C. (2021).",
      "``Econometric Identification Strategy.''",
      "\\textit{Review of Economic Studies}, 88(2), 567--601.",
      "\\bibitem[Smith(2023)]{smith2023}",
      "Smith, J. (2023).",
      "``Recent Advances in [Field].''",
      "\\textit{Journal of Political Economy}, 131(1), 1--45.",
      "\\end{thebibliography}",
      "",
      "\\appendix",
      "\\section{Proofs}",
      "\\subsection*{Proof of Proposition~\\ref{prop:exist}}",
      "Detailed proof here.",
      "",
      "\\section{Additional Tables and Figures}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  // ─── NEW: PHOTO CV / LOGO-READY TEMPLATES ──────────────────────────────────
  {
    id: "cv-photo",
    icon: "🖼️",
    title: "CV with Photo (2-column header)",
    category: "Career",
    desc: "Modern 2-column CV header: your photo or university logo on the right, name + links on the left. Replace the placeholder with \\includegraphics.",
    source: [
      "\\documentclass[10pt,a4paper]{article}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage{geometry}",
      "\\geometry{top=1.2cm, bottom=1.8cm, left=1.8cm, right=1.8cm}",
      "\\usepackage{graphicx}",
      "\\usepackage{hyperref}",
      "\\usepackage{enumitem}",
      "\\usepackage{xcolor}",
      "\\usepackage{booktabs}",
      "\\setlist{noitemsep, topsep=2pt}",
      "\\pagestyle{empty}",
      "",
      "% ── Colour palette (change to your institution's colours) ────────────────",
      "\\definecolor{headerblue}{RGB}{0, 56, 168}   % dark blue",
      "\\definecolor{accentgray}{RGB}{95,106,122}   % neutral gray",
      "",
      "% ── Section heading style ────────────────────────────────────────────────",
      "\\newcommand{\\cvsection}[1]{%",
      "  \\vspace{0.5em}",
      "  {\\large\\bfseries\\color{headerblue} #1}\\\\[-0.4em]",
      "  {\\color{headerblue}\\rule{\\linewidth}{0.8pt}}",
      "  \\vspace{0.3em}",
      "}",
      "",
      "\\begin{document}",
      "",
      "% ════════════════════════════════════════════════════════════════════════",
      "% HEADER",
      "% ════════════════════════════════════════════════════════════════════════",
      "\\begin{minipage}[c]{0.68\\linewidth}",
      "  {\\Huge\\bfseries\\color{headerblue} Your Full Name}\\\\[0.25em]",
      "  {\\large\\color{accentgray} PhD Candidate in Computer Science}\\\\[0.4em]",
      "  \\small",
      "  \\href{mailto:you@university.edu}{\\texttt{you@university.edu}}",
      "  \\textbullet{}",
      "  +33 6 00 00 00 00",
      "  \\textbullet{}",
      "  \\href{https://github.com/yourusername}{github.com/yourusername}\\\\",
      "  University Name, Department, City, Country",
      "\\end{minipage}",
      "\\hfill",
      "% ── RIGHT COLUMN: replace \\fbox with \\includegraphics ───────────────────",
      "\\begin{minipage}[c]{0.26\\linewidth}",
      "  \\centering",
      "  % ▼ HOW TO ADD YOUR PHOTO:",
      "  % 1. Put photo.jpg in the same folder as your .tex file",
      "  % 2. Uncomment the line below and delete the \\fbox placeholder",
      "  % \\includegraphics[width=\\linewidth, height=3.8cm, keepaspectratio, clip]{photo.jpg}",
      "  %",
      "  % ▼ OR: add your university logo instead of a photo:",
      "  % \\includegraphics[height=2cm]{university-logo.png}",
      "  \\fbox{\\parbox[c][3.8cm][c]{3.8cm}{\\centering\\color{accentgray}\\footnotesize Photo\\\\(3×4 cm)}}",
      "\\end{minipage}",
      "",
      "\\vspace{0.5em}",
      "{\\color{headerblue}\\rule{\\linewidth}{2pt}}",
      "\\vspace{0.5em}",
      "",
      "% ════════════════════════════════════════════════════════════════════════",
      "% BODY — two-column layout (left 62%, right 35%)",
      "% ════════════════════════════════════════════════════════════════════════",
      "\\begin{minipage}[t]{0.62\\linewidth}",
      "",
      "\\cvsection{Education}",
      "",
      "\\textbf{Ph.D. in Computer Science} \\hfill 2022 -- Present\\\\",
      "University Name, City, Country\\\\",
      "\\textit{Thesis: Your Thesis Title}\\\\",
      "\\textit{Supervisor: Prof.~Name}",
      "",
      "\\vspace{0.4em}",
      "\\textbf{M.Sc. in Mathematics} \\hfill 2020 -- 2022\\\\",
      "Another University, City, Country\\\\",
      "GPA: 4.0 / 4.0 --- Valedictorian",
      "",
      "\\cvsection{Publications}",
      "",
      "\\begin{enumerate}[leftmargin=*]",
      "  \\item \\textbf{Your Name}, Co-Author.",
      "  ``Title of Your Paper.''",
      "  \\textit{Journal / NeurIPS / ICML}, 2024.",
      "  \\href{https://doi.org/10.xxxx/xxxx}{\\texttt{[link]}}",
      "  \\item \\textbf{Your Name}, Co-Author.",
      "  ``Conference Paper Title.''",
      "  \\textit{ICLR Workshop}, 2023.",
      "\\end{enumerate}",
      "",
      "\\cvsection{Research Experience}",
      "",
      "\\textbf{Research Intern} \\hfill Jun -- Sep 2023\\\\",
      "Lab / Company Name, City\\\\",
      "Worked on [topic]: achieved [result].",
      "",
      "\\cvsection{Teaching}",
      "",
      "\\textbf{Teaching Assistant,} Machine Learning \\hfill Spring 2023\\\\",
      "60 students, weekly lab sessions, grading.",
      "",
      "\\end{minipage}",
      "\\hfill",
      "\\begin{minipage}[t]{0.34\\linewidth}",
      "",
      "\\cvsection{Skills}",
      "",
      "\\textbf{Languages}\\\\",
      "Python \\textbullet{} Julia \\textbullet{} C++\\\\",
      "MATLAB \\textbullet{} R",
      "",
      "\\vspace{0.3em}",
      "\\textbf{Frameworks}\\\\",
      "PyTorch \\textbullet{} JAX \\textbullet{} scikit-learn",
      "",
      "\\vspace{0.3em}",
      "\\textbf{Tools}\\\\",
      "Git \\textbullet{} Docker \\textbullet{} LaTeX\\\\",
      "Linux \\textbullet{} Slurm / HPC",
      "",
      "\\vspace{0.3em}",
      "\\textbf{Human Languages}\\\\",
      "English (C2) \\textbullet{} French (native)",
      "",
      "\\cvsection{Awards}",
      "",
      "\\begin{itemize}[leftmargin=*]",
      "  \\item Best Paper, Conf 2024",
      "  \\item PhD Fellowship, 2022",
      "  \\item Valedictorian, 2022",
      "\\end{itemize}",
      "",
      "\\cvsection{Links}",
      "",
      "\\small",
      "\\href{https://yourwebsite.com}{Personal website}\\\\",
      "\\href{https://scholar.google.com}{Google Scholar}\\\\",
      "\\href{https://linkedin.com/in/you}{LinkedIn}\\\\",
      "\\href{https://orcid.org/0000-0000-0000-0000}{ORCID}",
      "",
      "\\end{minipage}",
      "",
      "\\end{document}",
    ].join("\n"),
  },

  // ─── BEAMER WITH UNIVERSITY LOGO ────────────────────────────────────────────
  {
    id: "beamer-logo",
    icon: "🏫",
    title: "Beamer — University Presentation",
    category: "Slides",
    desc: "Beamer slide deck with university logo slots: \\titlegraphic and \\logo for title slide and every frame. Swap the placeholder with \\includegraphics.",
    source: [
      "\\documentclass{beamer}",
      "\\usetheme{Boadilla}",
      "\\usecolortheme{whale}",
      "\\usepackage{amsmath,amssymb}",
      "\\usepackage{graphicx}",
      "\\usepackage{booktabs}",
      "",
      "% ── LOGO CONFIGURATION ──────────────────────────────────────────────────",
      "% Appears on every slide (bottom-right corner):",
      "% \\logo{\\includegraphics[height=0.7cm]{university-logo.png}}",
      "%",
      "% Appears only on the title slide:",
      "% \\titlegraphic{\\includegraphics[height=1.5cm]{university-logo.png}\\hspace{1cm}\\includegraphics[height=1.5cm]{lab-logo.png}}",
      "%",
      "% HOW TO USE:",
      "% 1. Put your logo file (PNG/PDF/EPS) in the same folder as your .tex",
      "% 2. Remove the % from the lines above",
      "% 3. Adjust height= to fit your logo",
      "% ────────────────────────────────────────────────────────────────────────",
      "",
      "% Placeholder logo (delete once you add a real logo):",
      "\\titlegraphic{\\fbox{\\parbox[c][1.2cm][c]{3cm}{\\centering\\tiny University Logo\\\\(replace me)}}}",
      "",
      "\\title[Short Title]{Full Title of Your Research}",
      "\\subtitle{Conference Name $\\cdot$ City, Month Year}",
      "\\author[Your Name]{Your Full Name}",
      "\\institute[Dept.]{%",
      "  Department of XYZ\\\\",
      "  University Name\\\\[0.2em]",
      "  \\texttt{you@university.edu}",
      "}",
      "\\date{\\today}",
      "",
      "\\begin{document}",
      "",
      "\\begin{frame}",
      "  \\titlepage",
      "\\end{frame}",
      "",
      "\\begin{frame}{Outline}",
      "  \\tableofcontents",
      "\\end{frame}",
      "",
      "\\section{Introduction}",
      "",
      "\\begin{frame}{Motivation}",
      "  \\begin{itemize}",
      "    \\item<1-> Why is this problem important?",
      "    \\item<2-> What gap does this work address?",
      "    \\item<3-> Our key contributions:",
      "    \\begin{itemize}",
      "      \\item Novel method for [X] with theoretical guarantees",
      "      \\item Empirical validation on [benchmark]",
      "    \\end{itemize}",
      "  \\end{itemize}",
      "\\end{frame}",
      "",
      "\\section{Method}",
      "",
      "\\begin{frame}{Problem Formulation}",
      "  \\begin{block}{Setup}",
      "    Given input $\\mathbf{x} \\in \\mathbb{R}^d$, we minimize the objective:",
      "  \\end{block}",
      "  \\[",
      "    \\mathcal{L}(\\theta) = \\frac{1}{n}\\sum_{i=1}^n \\ell(f_\\theta(\\mathbf{x}_i), y_i)",
      "    + \\lambda \\|\\theta\\|_2^2",
      "  \\]",
      "  where $\\lambda > 0$ controls regularisation.",
      "\\end{frame}",
      "",
      "\\begin{frame}{Algorithm}",
      "  \\begin{columns}[T]",
      "    \\begin{column}{0.55\\linewidth}",
      "      \\textbf{Key steps:}",
      "      \\begin{enumerate}",
      "        \\item Initialise $\\theta_0$",
      "        \\item For each mini-batch $\\mathcal{B}$:",
      "        \\[",
      "          \\theta_{t+1} = \\theta_t - \\alpha \\nabla_{\\mathcal{B}} \\mathcal{L}(\\theta_t)",
      "        \\]",
      "        \\item Evaluate on validation set",
      "      \\end{enumerate}",
      "    \\end{column}",
      "    \\begin{column}{0.40\\linewidth}",
      "      \\begin{block}{Complexity}",
      "        $O(n \\log n)$ per epoch\\\\",
      "        Memory: $O(d)$",
      "      \\end{block}",
      "    \\end{column}",
      "  \\end{columns}",
      "\\end{frame}",
      "",
      "\\section{Results}",
      "",
      "\\begin{frame}{Experimental Results}",
      "  \\begin{table}",
      "    \\centering",
      "    \\begin{tabular}{lcc}",
      "      \\toprule",
      "      Method & Accuracy & Time (s) \\\\",
      "      \\midrule",
      "      Baseline & 88.4\\% & 12.3 \\\\",
      "      Method X & 91.2\\% & 10.7 \\\\",
      "      \\textbf{Ours} & \\textbf{94.7\\%} & \\textbf{8.9} \\\\",
      "      \\bottomrule",
      "    \\end{tabular}",
      "  \\end{table}",
      "  \\vspace{0.5em}",
      "  \\begin{alertblock}{Key result}",
      "    Our method achieves \\textbf{+6.3\\%} accuracy with \\textbf{28\\%} less compute.",
      "  \\end{alertblock}",
      "\\end{frame}",
      "",
      "\\section{Conclusion}",
      "",
      "\\begin{frame}{Conclusion \\& Future Work}",
      "  \\begin{columns}",
      "    \\begin{column}{0.5\\linewidth}",
      "      \\textbf{What we showed:}",
      "      \\begin{itemize}",
      "        \\item Novel method for [X]",
      "        \\item State-of-the-art on [benchmarks]",
      "        \\item Theoretical convergence guarantee",
      "      \\end{itemize}",
      "    \\end{column}",
      "    \\begin{column}{0.5\\linewidth}",
      "      \\textbf{Future work:}",
      "      \\begin{itemize}",
      "        \\item Extend to [larger scale]",
      "        \\item Apply to [new domain]",
      "        \\item Open-source release",
      "      \\end{itemize}",
      "    \\end{column}",
      "  \\end{columns}",
      "  \\vspace{1em}",
      "  \\centering{\\Large\\bfseries Thank you! Questions?}\\\\[0.5em]",
      "  \\small\\texttt{you@university.edu}",
      "\\end{frame}",
      "",
      "\\end{document}",
    ].join("\n"),
  },

  // ─── ML CONFERENCE PAPER (NeurIPS / ICML / ICLR style) ─────────────────────
  {
    id: "ml-conference",
    icon: "🤖",
    title: "ML Conference Paper (NeurIPS / ICML / ICLR style)",
    category: "Research",
    desc: "Standard ML conference paper layout: anonymous review header, two-column abstract, contributions paragraph, algorithm environment, and appendix. Works as a drop-in before uploading the official class.",
    source: [
      "% ─────────────────────────────────────────────────────────────────────────",
      "% ML CONFERENCE PAPER TEMPLATE",
      "% Works for NeurIPS / ICML / ICLR / CVPR / AAAI submissions.",
      "%",
      "% To use the official style file:",
      "%   NeurIPS  → \\usepackage{neurips_2025}",
      "%   ICML     → \\usepackage{icml2025}",
      "%   ICLR     → \\usepackage{iclr2025_conference}",
      "% Download from the conference website and place next to this .tex file.",
      "% ─────────────────────────────────────────────────────────────────────────",
      "\\documentclass{article}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage[margin=2.5cm, top=2.5cm]{geometry}",
      "\\usepackage{amsmath,amssymb,amsthm}",
      "\\usepackage{graphicx}",
      "\\usepackage{booktabs}",
      "\\usepackage[hidelinks]{hyperref}",
      "\\usepackage{algorithm}",
      "\\usepackage{algorithmic}",
      "\\usepackage{microtype}",
      "\\usepackage{xcolor}",
      "\\usepackage{natbib}",
      "\\bibliographystyle{abbrvnat}",
      "",
      "% ── Anonymous submission header (remove for camera-ready) ───────────────",
      "\\title{\\textbf{Title of Your Paper}\\\\",
      "  \\large Submitted to [Conference Year] --- Under Review}",
      "",
      "% For camera-ready, replace with real author block:",
      "% \\author{",
      "%   First Author\\thanks{Equal contribution.} \\And Second Author \\AND Third Author \\\\",
      "%   University Name \\quad\\quad Lab / Affiliation \\\\",
      "%   \\texttt{\\{first,second\\}@university.edu}",
      "% }",
      "\\author{Anonymous Authors}",
      "\\date{}",
      "",
      "% ── Custom commands ─────────────────────────────────────────────────────",
      "\\newcommand{\\R}{\\mathbb{R}}",
      "\\newcommand{\\E}{\\mathbb{E}}",
      "\\newcommand{\\norm}[1]{\\left\\|#1\\right\\|}",
      "\\newcommand{\\KL}[2]{D_{\\mathrm{KL}}\\left(#1\\,\\|\\,#2\\right)}",
      "",
      "% ── Theorem environments ────────────────────────────────────────────────",
      "\\newtheorem{theorem}{Theorem}",
      "\\newtheorem{lemma}[theorem]{Lemma}",
      "\\newtheorem{proposition}[theorem]{Proposition}",
      "\\newtheorem{corollary}[theorem]{Corollary}",
      "\\theoremstyle{definition}",
      "\\newtheorem{definition}{Definition}",
      "\\theoremstyle{remark}",
      "\\newtheorem{remark}{Remark}",
      "",
      "\\begin{document}",
      "\\maketitle",
      "",
      "% ── Abstract ────────────────────────────────────────────────────────────",
      "\\begin{abstract}",
      "We address [the problem] in the setting of [context].",
      "Our main contribution is [method/result], which achieves [metric] on [benchmark],",
      "outperforming prior work by [margin]. We provide theoretical guarantees showing [guarantee].",
      "Code will be released at \\texttt{https://github.com/anonymous/repo}.",
      "\\end{abstract}",
      "",
      "% ── 1. Introduction ─────────────────────────────────────────────────────",
      "\\section{Introduction}",
      "\\label{sec:intro}",
      "",
      "Start with the problem and why it matters.",
      "\\citet{vaswani2017attention} introduced the transformer architecture;",
      "subsequent work \\citep{devlin2019bert,brown2020language} showed...",
      "",
      "\\paragraph{Contributions.}",
      "Our main contributions are:",
      "\\begin{enumerate}",
      "  \\item[(i)] A novel [method] that [property] (Section~\\ref{sec:method}).",
      "  \\item[(ii)] Theoretical analysis proving \\emph{[convergence rate]}",
      "    (Theorem~\\ref{thm:main}).",
      "  \\item[(iii)] Empirical evaluation showing \\emph{state-of-the-art} on",
      "    [benchmark] (Section~\\ref{sec:experiments}).",
      "\\end{enumerate}",
      "",
      "% ── 2. Related Work ─────────────────────────────────────────────────────",
      "\\section{Related Work}",
      "\\label{sec:related}",
      "",
      "\\paragraph{[Topic A].}",
      "Prior work by \\citet{lecun1998gradient} established [result].",
      "More recently, \\citet{he2016deep} showed [finding].",
      "",
      "\\paragraph{[Topic B].}",
      "Our work differs from \\citet{goodfellow2016deep} in that [key difference].",
      "",
      "% ── 3. Method ───────────────────────────────────────────────────────────",
      "\\section{Method}",
      "\\label{sec:method}",
      "",
      "\\subsection{Problem Setup}",
      "",
      "Let $\\mathcal{X} \\subset \\R^d$ denote the input space and",
      "$\\mathcal{Y}$ the label space.",
      "We observe $n$ i.i.d.~samples $(\\mathbf{x}_i, y_i)_{i=1}^n$ drawn from",
      "distribution $\\mathcal{D}$ over $\\mathcal{X} \\times \\mathcal{Y}$.",
      "Our goal is to minimise the expected risk:",
      "\\[",
      "  \\mathcal{R}(f) = \\E_{(\\mathbf{x},y) \\sim \\mathcal{D}}[\\ell(f(\\mathbf{x}), y)]",
      "\\]",
      "",
      "\\subsection{Proposed Algorithm}",
      "",
      "\\begin{algorithm}[h]",
      "  \\caption{[Your Algorithm Name]}",
      "  \\label{alg:main}",
      "  \\begin{algorithmic}[1]",
      "    \\STATE \\textbf{Input:} Dataset $\\{(\\mathbf{x}_i, y_i)\\}_{i=1}^n$,",
      "      learning rate $\\eta > 0$, iterations $T$",
      "    \\STATE Initialise parameters $\\theta_0 \\in \\R^p$",
      "    \\FOR{$t = 1, \\ldots, T$}",
      "      \\STATE Sample mini-batch $\\mathcal{B} \\subset [n]$, $|\\mathcal{B}| = b$",
      "      \\STATE Compute gradient $\\mathbf{g}_t = \\frac{1}{b}\\sum_{i \\in \\mathcal{B}}",
      "        \\nabla_\\theta \\ell(f_\\theta(\\mathbf{x}_i), y_i)$",
      "      \\STATE Update $\\theta_{t+1} = \\theta_t - \\eta \\mathbf{g}_t$",
      "    \\ENDFOR",
      "    \\RETURN $\\theta_T$",
      "  \\end{algorithmic}",
      "\\end{algorithm}",
      "",
      "\\subsection{Theoretical Analysis}",
      "",
      "\\begin{theorem}",
      "  \\label{thm:main}",
      "  Under Assumptions [A1--A3], Algorithm~\\ref{alg:main} satisfies:",
      "  \\[",
      "    \\E[\\mathcal{R}(f_{\\theta_T})] - \\mathcal{R}^* \\leq",
      "    \\frac{\\|\\theta_0 - \\theta^*\\|^2}{2\\eta T} + \\frac{\\eta L \\sigma^2}{2}",
      "  \\]",
      "  where $L$ is the Lipschitz constant and $\\sigma^2$ is the gradient variance.",
      "\\end{theorem}",
      "\\begin{proof}",
      "  By the descent lemma for $L$-smooth functions and telescoping. $\\square$",
      "\\end{proof}",
      "",
      "% ── 4. Experiments ──────────────────────────────────────────────────────",
      "\\section{Experiments}",
      "\\label{sec:experiments}",
      "",
      "\\subsection{Setup}",
      "",
      "\\textbf{Datasets.}",
      "We evaluate on [Dataset A] ($n$ = X, $d$ = Y) and [Dataset B] ($n$ = X).",
      "",
      "\\textbf{Baselines.}",
      "We compare against: (1) Method A \\citep{ref1}; (2) Method B \\citep{ref2};",
      "(3) Method C (our ablation).",
      "",
      "\\textbf{Implementation.}",
      "All models trained on [hardware] with [framework]. Hyper-parameters selected via",
      "cross-validation; see Appendix~\\ref{app:hparams} for details.",
      "",
      "\\subsection{Main Results}",
      "",
      "Table~\\ref{tab:main} shows that our method achieves state-of-the-art on all benchmarks.",
      "",
      "\\begin{table}[t]",
      "  \\centering",
      "  \\caption{Comparison on [task]. Higher is better ($\\uparrow$). Best in \\textbf{bold}.}",
      "  \\label{tab:main}",
      "  \\begin{tabular}{lcccc}",
      "    \\toprule",
      "    Method & Acc.~(\\%) $\\uparrow$ & F1 $\\uparrow$ & Params & FLOPs \\\\",
      "    \\midrule",
      "    Baseline~\\citep{ref1} & 88.4 & 0.879 & 25M & 4.1G \\\\",
      "    Method B~\\citep{ref2} & 91.2 & 0.908 & 67M & 11.3G \\\\",
      "    \\midrule",
      "    \\textbf{Ours} & \\textbf{94.7} & \\textbf{0.943} & \\textbf{18M} & \\textbf{2.8G} \\\\",
      "    \\bottomrule",
      "  \\end{tabular}",
      "\\end{table}",
      "",
      "\\subsection{Ablation Study}",
      "",
      "We isolate the contribution of each component in Table~\\ref{tab:ablation}.",
      "",
      "\\begin{table}[t]",
      "  \\centering",
      "  \\caption{Ablation on [Dataset A].}",
      "  \\label{tab:ablation}",
      "  \\begin{tabular}{lcc}",
      "    \\toprule",
      "    Variant & Acc. & $\\Delta$ \\\\",
      "    \\midrule",
      "    Full model & 94.7\\% & --- \\\\",
      "    w/o component A & 92.1\\% & $-$2.6 \\\\",
      "    w/o component B & 90.8\\% & $-$3.9 \\\\",
      "    \\bottomrule",
      "  \\end{tabular}",
      "\\end{table}",
      "",
      "% ── 5. Conclusion ───────────────────────────────────────────────────────",
      "\\section{Conclusion}",
      "We proposed [method], achieving [result]. Future work includes [direction].",
      "",
      "% ── References ──────────────────────────────────────────────────────────",
      "\\begin{thebibliography}{9}",
      "\\bibitem[Vaswani et al.(2017)]{vaswani2017attention}",
      "Vaswani, A., Shazeer, N., Parmar, N., et al. (2017).",
      "\\textit{Attention Is All You Need}.",
      "NeurIPS.",
      "\\bibitem[Brown et al.(2020)]{brown2020language}",
      "Brown, T., Mann, B., Ryder, N., et al. (2020).",
      "\\textit{Language Models are Few-Shot Learners}.",
      "NeurIPS.",
      "\\bibitem[He et al.(2016)]{he2016deep}",
      "He, K., Zhang, X., Ren, S., Sun, J. (2016).",
      "\\textit{Deep Residual Learning for Image Recognition}.",
      "CVPR.",
      "\\end{thebibliography}",
      "",
      "% ── Appendix ────────────────────────────────────────────────────────────",
      "\\appendix",
      "\\section{Proofs}",
      "\\label{app:proofs}",
      "",
      "\\textbf{Proof of Theorem~\\ref{thm:main}.}",
      "Full derivation here.",
      "",
      "\\section{Hyper-parameter Settings}",
      "\\label{app:hparams}",
      "",
      "\\begin{table}[h]",
      "  \\centering",
      "  \\begin{tabular}{lcc}",
      "    \\toprule",
      "    Hyper-parameter & Dataset A & Dataset B \\\\",
      "    \\midrule",
      "    Learning rate & $10^{-3}$ & $5\\times10^{-4}$ \\\\",
      "    Batch size & 256 & 128 \\\\",
      "    Epochs & 200 & 100 \\\\",
      "    \\bottomrule",
      "  \\end{tabular}",
      "\\end{table}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
];

export const CATEGORIES = ["All", "Thesis", "Research", "Career", "Slides", "Homework", "Grande École"];

