export interface Template {
  id: string;
  icon: string;
  title: string;
  category: string;
  desc: string;
  source: string;
}

export const TEMPLATES: Template[] = [
  {
    id: "article",
    icon: "📝",
    title: "Academic Article",
    category: "Research",
    desc: "Standard article with abstract, sections, math equations, and bibliography.",
    source: [
      "\\documentclass[12pt,a4paper]{article}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage{amsmath,amssymb,amsthm}",
      "\\usepackage{hyperref}",
      "\\usepackage{geometry}",
      "\\geometry{margin=2.5cm}",
      "",
      "\\title{\\textbf{Title of Your Paper}\\\\",
      "  \\large Subtitle or Affiliation}",
      "\\author{First Author\\thanks{Corresponding author: email@university.edu} \\and Second Author}",
      "\\date{\\today}",
      "",
      "\\begin{document}",
      "",
      "\\maketitle",
      "",
      "\\begin{abstract}",
      "This paper presents a study of... Write your abstract here, summarizing the main contributions, methodology, and results. Keep it concise — typically 150–300 words.",
      "\\end{abstract}",
      "",
      "\\section{Introduction}",
      "",
      "Write your introduction here. Reference prior work \\cite{smith2023} and state your contributions clearly.",
      "",
      "\\section{Methodology}",
      "",
      "Describe your methods. You can include equations:",
      "",
      "\\begin{equation}",
      "  E = mc^2",
      "\\end{equation}",
      "",
      "And more complex ones:",
      "",
      "\\[",
      "  \\int_0^\\infty e^{-x^2}\\,dx = \\frac{\\sqrt{\\pi}}{2}",
      "\\]",
      "",
      "\\subsection{Experimental Setup}",
      "",
      "Describe your experimental setup here.",
      "",
      "\\section{Results}",
      "",
      "Present your results. Consider adding tables and figures.",
      "",
      "\\section{Conclusion}",
      "",
      "Summarize your findings and future work.",
      "",
      "\\begin{thebibliography}{9}",
      "\\bibitem{smith2023} Smith, J. (2023). \\textit{A great paper}. Journal of Things, 42(1), 1--10.",
      "\\end{thebibliography}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "cv",
    icon: "👤",
    title: "Academic CV",
    category: "Career",
    desc: "Clean CV template for researchers and academics with publications section.",
    source: [
      "\\documentclass[11pt,a4paper]{article}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage{geometry}",
      "\\geometry{margin=2cm}",
      "\\usepackage{hyperref}",
      "\\usepackage{enumitem}",
      "\\setlist{noitemsep}",
      "\\pagestyle{empty}",
      "",
      "\\begin{document}",
      "",
      "{\\LARGE \\textbf{Your Name}}\\\\[0.3em]",
      "{\\large Researcher -- University Name}\\\\[0.2em]",
      "\\href{mailto:you@university.edu}{you@university.edu}",
      "+1 (555) 000-0000",
      "",
      "\\hrule\\vspace{0.5em}",
      "",
      "\\section*{Education}",
      "",
      "\\textbf{Ph.D. in Computer Science} \\hfill 2020 -- Present\\\\",
      "University Name, City, Country\\\\",
      "\\textit{Thesis: Title of your dissertation}",
      "",
      "\\textbf{M.Sc. in Mathematics} \\hfill 2018 -- 2020\\\\",
      "Another University, City, Country",
      "",
      "\\section*{Research Interests}",
      "",
      "Machine learning, optimization, numerical methods, scientific computing.",
      "",
      "\\section*{Publications}",
      "",
      "\\begin{enumerate}",
      "  \\item \\textbf{Your Name}, Co-Author. ``Paper Title.'' \\textit{Journal Name}, vol. 42, 2023.",
      "  \\item \\textbf{Your Name}, Co-Author. ``Conference Paper.'' \\textit{NeurIPS}, 2022.",
      "\\end{enumerate}",
      "",
      "\\section*{Experience}",
      "",
      "\\textbf{Research Intern} \\hfill Summer 2022\\\\",
      "Company / Lab Name, City\\\\",
      "Worked on relevant problems in the field.",
      "",
      "\\section*{Skills}",
      "",
      "\\textbf{Programming:} Python, Julia, MATLAB, C++\\\\",
      "\\textbf{Tools:} LaTeX, Git, Linux, Docker\\\\",
      "\\textbf{Languages:} English (fluent), French (native)",
      "",
      "\\section*{Awards}",
      "",
      "\\begin{itemize}",
      "  \\item Best Paper Award, SomeConference 2023",
      "  \\item Research Fellowship, University Name, 2021",
      "\\end{itemize}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "beamer",
    icon: "📊",
    title: "Beamer Presentation",
    category: "Slides",
    desc: "Clean Beamer slide deck with title slide, table of contents, and math.",
    source: [
      "\\documentclass{beamer}",
      "\\usetheme{Madrid}",
      "\\usecolortheme{seahorse}",
      "\\usepackage{amsmath,amssymb}",
      "",
      "\\title[Short Title]{Full Title of Your Presentation}",
      "\\subtitle{Subtitle or Conference Name}",
      "\\author{Your Name}",
      "\\institute{University or Department}",
      "\\date{\\today}",
      "",
      "\\begin{document}",
      "",
      "\\begin{frame}",
      "  \\titlepage",
      "\\end{frame}",
      "",
      "\\begin{frame}{Table of Contents}",
      "  \\tableofcontents",
      "\\end{frame}",
      "",
      "\\section{Introduction}",
      "",
      "\\begin{frame}{Motivation}",
      "  \\begin{itemize}",
      "    \\item Why is this problem important?",
      "    \\item What gap does this work address?",
      "    \\item Key challenges we overcome:",
      "    \\begin{itemize}",
      "      \\item Challenge 1",
      "      \\item Challenge 2",
      "    \\end{itemize}",
      "  \\end{itemize}",
      "\\end{frame}",
      "",
      "\\section{Method}",
      "",
      "\\begin{frame}{Our Approach}",
      "  \\begin{block}{Main Idea}",
      "    We propose a method based on the following key insight...",
      "  \\end{block}",
      "",
      "  The gradient descent update is:",
      "  \\[",
      "    x_{n+1} = x_n - \\alpha \\nabla f(x_n)",
      "  \\]",
      "",
      "  where $\\alpha$ is the learning rate.",
      "\\end{frame}",
      "",
      "\\section{Results}",
      "",
      "\\begin{frame}{Experimental Results}",
      "  Dataset A: Accuracy 94.2\\%, F1 Score 0.941\\\\",
      "  Dataset B: Accuracy 91.7\\%, F1 Score 0.918",
      "\\end{frame}",
      "",
      "\\section{Conclusion}",
      "",
      "\\begin{frame}{Conclusion}",
      "  \\begin{itemize}",
      "    \\item We presented a novel approach to...",
      "    \\item Our method outperforms baselines on X benchmarks",
      "    \\item Future work: extension to larger datasets",
      "  \\end{itemize}",
      "  \\vspace{1.5em}",
      "  \\centering \\Large \\textbf{Thank you! Questions?}",
      "\\end{frame}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "math-assignment",
    icon: "🧮",
    title: "Math Assignment",
    category: "Homework",
    desc: "Problem set template with theorem/proof environments and custom commands.",
    source: [
      "\\documentclass[12pt]{article}",
      "\\usepackage{amsmath,amssymb,amsthm}",
      "\\usepackage{geometry}",
      "\\geometry{margin=2.5cm}",
      "\\usepackage{enumitem}",
      "",
      "% Custom commands",
      "\\newcommand{\\R}{\\mathbb{R}}",
      "\\newcommand{\\N}{\\mathbb{N}}",
      "\\newcommand{\\Z}{\\mathbb{Z}}",
      "\\newcommand{\\eps}{\\varepsilon}",
      "",
      "% Theorem environments",
      "\\newtheorem{theorem}{Theorem}",
      "\\newtheorem{lemma}[theorem]{Lemma}",
      "\\theoremstyle{definition}",
      "\\newtheorem{definition}{Definition}",
      "",
      "\\title{Problem Set 3}",
      "\\author{Your Name}",
      "\\date{Due: \\today}",
      "",
      "\\begin{document}",
      "\\maketitle",
      "",
      "\\section*{Problem 1}",
      "",
      "Prove that every bounded sequence in $\\R^n$ has a convergent subsequence.",
      "",
      "\\textbf{Proof.}",
      "We proceed by induction on $n$.",
      "",
      "\\textbf{Base case} ($n=1$): By the Bolzano-Weierstrass theorem, every bounded sequence",
      "in $\\R$ has a convergent subsequence.",
      "",
      "\\textbf{Inductive step}: Assume the result holds for $\\R^{n-1}$. Let $(\\mathbf{x}_k)$",
      "be a bounded sequence in $\\R^n$. The projection onto the first coordinate is bounded in $\\R$,",
      "so it has a convergent subsequence by the base case. $\\square$",
      "",
      "\\section*{Problem 2}",
      "",
      "Let $f: \\R \\to \\R$ be differentiable. Show that if $|f'(x)| \\leq M$ for all $x$, then:",
      "",
      "\\[",
      "  |f(x) - f(y)| \\leq M|x - y| \\quad \\text{for all } x, y \\in \\R",
      "\\]",
      "",
      "\\textbf{Proof.}",
      "By the Mean Value Theorem, there exists $c$ between $x$ and $y$ such that",
      "$f(x) - f(y) = f'(c)(x-y)$.",
      "Taking absolute values gives $|f(x) - f(y)| \\leq M|x-y|$. $\\square$",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "letter",
    icon: "✉️",
    title: "Cover Letter",
    category: "Career",
    desc: "Professional cover letter for academic or industry job applications.",
    source: [
      "\\documentclass[11pt,a4paper]{article}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage{geometry}",
      "\\geometry{margin=2.5cm}",
      "",
      "\\begin{document}",
      "",
      "\\noindent",
      "\\textbf{Your Name}\\\\",
      "Department, University\\\\",
      "City, Country\\\\",
      "you@example.com",
      "",
      "\\vspace{1em}",
      "\\noindent \\today",
      "",
      "\\vspace{1em}",
      "\\noindent",
      "Hiring Manager\\\\",
      "Company / Department\\\\",
      "City, Country",
      "",
      "\\vspace{1em}",
      "\\noindent Dear Hiring Committee,",
      "",
      "I am writing to apply for the position of [Role] at [Organization].",
      "I am currently a [your status] at [institution], specializing in [your field].",
      "",
      "My research focuses on [describe your research in 1-2 sentences].",
      "I believe my background in [skills/areas] makes me a strong candidate for this position.",
      "",
      "During my time at [previous institution/company], I [achievement 1].",
      "Additionally, I [achievement 2].",
      "These experiences have equipped me with [skills] directly applicable to your team's work.",
      "",
      "I am particularly drawn to [Organization] because [specific reason].",
      "I am confident that I could contribute meaningfully to [specific project or goal].",
      "",
      "I have attached my CV and would welcome the opportunity to discuss further.",
      "",
      "\\vspace{1em}",
      "\\noindent Sincerely,\\\\[2em]",
      "\\noindent \\textbf{Your Name}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "physics",
    icon: "⚛️",
    title: "Physics Lab Report",
    category: "Research",
    desc: "Structured lab report with error analysis, tables, and SI units.",
    source: [
      "\\documentclass[12pt,a4paper]{article}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage{amsmath,amssymb}",
      "\\usepackage{siunitx}",
      "\\usepackage{booktabs}",
      "\\usepackage{geometry}",
      "\\geometry{margin=2.5cm}",
      "",
      "\\title{Lab Report: Measurement of Gravitational Acceleration}",
      "\\author{Student Name \\\\ Partner Name}",
      "\\date{\\today}",
      "",
      "\\begin{document}",
      "\\maketitle",
      "",
      "\\section{Objective}",
      "",
      "Determine the local gravitational acceleration $g$ using a simple pendulum,",
      "and compare the result to the accepted value of",
      "$g = \\SI{9.81}{m/s^2}$.",
      "",
      "\\section{Theory}",
      "",
      "For small oscillations, the period $T$ of a simple pendulum of length $L$ is:",
      "",
      "\\[",
      "  T = 2\\pi\\sqrt{\\frac{L}{g}}",
      "\\]",
      "",
      "Solving for $g$:",
      "",
      "\\[",
      "  g = \\frac{4\\pi^2 L}{T^2}",
      "\\]",
      "",
      "\\section{Data}",
      "",
      "\\begin{table}[h]",
      "\\centering",
      "\\begin{tabular}{ccc}",
      "\\toprule",
      "Trial & Length $L$ (m) & Period $T$ (s) \\\\",
      "\\midrule",
      "1 & 0.500 & 1.421 \\\\",
      "2 & 0.500 & 1.419 \\\\",
      "3 & 0.500 & 1.423 \\\\",
      "\\midrule",
      "Mean & 0.500 & 1.421 \\\\",
      "\\bottomrule",
      "\\end{tabular}",
      "\\caption{Pendulum period measurements at fixed length $L = \\SI{0.500}{m}$.}",
      "\\end{table}",
      "",
      "\\section{Results}",
      "",
      "Using $L = \\SI{0.500}{m}$ and $T = \\SI{1.421}{s}$:",
      "",
      "\\[",
      "  g = \\frac{4\\pi^2 \\times 0.500}{(1.421)^2} = \\SI{9.78}{m/s^2}",
      "\\]",
      "",
      "\\section{Error Analysis}",
      "",
      "The percentage error relative to the accepted value is:",
      "\\[",
      "  \\text{error} = \\frac{|9.78 - 9.81|}{9.81} \\times 100\\% = 0.31\\%",
      "\\]",
      "",
      "\\section{Conclusion}",
      "",
      "The measured value $g = \\SI{9.78}{m/s^2}$ agrees with the accepted value",
      "to within experimental uncertainty. Main sources of error: air resistance,",
      "timing reaction delay, and non-zero amplitude.",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  // ─── ACADEMIC / THESIS ───────────────────────────────────────────────────
  {
    id: "phd-thesis",
    icon: "🎓",
    title: "PhD Thesis",
    category: "Thesis",
    desc: "Full doctoral thesis structure: title page, abstract, ToC, chapters, appendices, and bibliography.",
    source: [
      "\\documentclass[12pt, a4paper, twoside]{report}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage{geometry}",
      "\\geometry{inner=3.5cm, outer=2.5cm, top=2.5cm, bottom=2.5cm}",
      "\\usepackage{setspace}",
      "\\onehalfspacing",
      "\\usepackage{graphicx}",
      "\\usepackage{amsmath, amssymb, amsthm}",
      "\\usepackage[hidelinks]{hyperref}",
      "\\usepackage{booktabs}",
      "\\usepackage{microtype}",
      "\\usepackage{fancyhdr}",
      "\\pagestyle{fancy}",
      "",
      "% Theorem environments",
      "\\newtheorem{theorem}{Theorem}[chapter]",
      "\\newtheorem{lemma}[theorem]{Lemma}",
      "\\newtheorem{proposition}[theorem]{Proposition}",
      "\\theoremstyle{definition}",
      "\\newtheorem{definition}{Definition}[chapter]",
      "",
      "\\begin{document}",
      "",
      "% ── Title page ──────────────────────────────",
      "\\begin{titlepage}",
      "  \\centering",
      "  {\\Large University Name}\\\\[1cm]",
      "  {\\Huge \\textbf{Your Thesis Title}}\\\\[0.5cm]",
      "  {\\large Subtitle if applicable}\\\\[2cm]",
      "  {\\normalsize A thesis submitted in partial fulfillment of\\\\",
      "  the requirements for the degree of}\\\\[0.5cm]",
      "  {\\Large \\textbf{Doctor of Philosophy}}\\\\[0.5cm]",
      "  in\\\\[0.3cm]",
      "  {\\large Department of XYZ}\\\\[2cm]",
      "  {\\normalsize by}\\\\[0.3cm]",
      "  {\\large \\textbf{Your Full Name}}\\\\[3cm]",
      "  Supervisor: Prof. Supervisor Name\\\\[0.5cm]",
      "  {\\today}",
      "\\end{titlepage}",
      "",
      "% ── Front matter ────────────────────────────",
      "\\chapter*{Declaration}",
      "I hereby declare that this thesis is my own original work...",
      "\\newpage",
      "",
      "\\chapter*{Abstract}",
      "\\addcontentsline{toc}{chapter}{Abstract}",
      "Your abstract goes here (300--500 words). Summarize your research question,",
      "methodology, key findings, and contribution to the field.",
      "",
      "\\chapter*{Acknowledgements}",
      "\\addcontentsline{toc}{chapter}{Acknowledgements}",
      "I would like to thank my supervisor, Prof. Name, for invaluable guidance...",
      "",
      "\\tableofcontents",
      "\\listoffigures",
      "\\listoftables",
      "",
      "% ── Chapter 1: Introduction ─────────────────",
      "\\chapter{Introduction}",
      "\\label{chap:intro}",
      "",
      "\\section{Background and Motivation}",
      "Introduce your research area and why it matters. Reference prior work \\cite{smith2023}.",
      "",
      "\\section{Research Questions}",
      "\\begin{enumerate}",
      "  \\item RQ1: How does X affect Y?",
      "  \\item RQ2: Can Z be efficiently computed under condition W?",
      "\\end{enumerate}",
      "",
      "\\section{Contributions}",
      "The main contributions of this thesis are:",
      "\\begin{itemize}",
      "  \\item A novel framework for...",
      "  \\item Theoretical analysis proving...",
      "  \\item Empirical validation on...",
      "\\end{itemize}",
      "",
      "\\section{Thesis Structure}",
      "Chapter~\\ref{chap:review} reviews related work.",
      "Chapter~\\ref{chap:method} describes our methodology.",
      "",
      "% ── Chapter 2: Literature Review ────────────",
      "\\chapter{Literature Review}",
      "\\label{chap:review}",
      "",
      "\\section{Overview}",
      "\\subsection{Prior Work on Topic A}",
      "\\subsection{Prior Work on Topic B}",
      "",
      "% ── Chapter 3: Methodology ──────────────────",
      "\\chapter{Methodology}",
      "\\label{chap:method}",
      "",
      "\\section{Research Design}",
      "",
      "\\section{Mathematical Framework}",
      "Let $\\mathcal{X}$ denote the input space. We define:",
      "\\begin{definition}",
      "  A function $f: \\mathcal{X} \\to \\mathbb{R}$ is \\emph{Lipschitz continuous}",
      "  with constant $L$ if for all $x, y \\in \\mathcal{X}$:",
      "  \\[",
      "    |f(x) - f(y)| \\leq L\\|x - y\\|",
      "  \\]",
      "\\end{definition}",
      "",
      "\\begin{theorem}",
      "  State your main theorem here.",
      "\\end{theorem}",
      "\\begin{proof}",
      "  Proof details here. $\\qed$",
      "\\end{proof}",
      "",
      "% ── Chapter 4: Results ──────────────────────",
      "\\chapter{Results}",
      "\\label{chap:results}",
      "",
      "\\section{Main Findings}",
      "",
      "\\begin{table}[ht]",
      "  \\centering",
      "  \\caption{Comparison of methods on benchmark datasets.}",
      "  \\begin{tabular}{lccc}",
      "    \\toprule",
      "    Method & Dataset A & Dataset B & Runtime (s) \\\\",
      "    \\midrule",
      "    Baseline & 0.75 & 0.71 & 12.3 \\\\",
      "    Method X & 0.84 & 0.82 & 15.1 \\\\",
      "    Ours & \\textbf{0.92} & \\textbf{0.89} & 18.4 \\\\",
      "    \\bottomrule",
      "  \\end{tabular}",
      "  \\label{tab:results}",
      "\\end{table}",
      "",
      "% ── Chapter 5: Discussion ───────────────────",
      "\\chapter{Discussion}",
      "\\label{chap:discussion}",
      "",
      "\\section{Interpretation}",
      "\\section{Limitations}",
      "\\section{Future Work}",
      "",
      "% ── Chapter 6: Conclusion ───────────────────",
      "\\chapter{Conclusion}",
      "\\label{chap:conclusion}",
      "",
      "\\section{Summary of Contributions}",
      "\\section{Future Directions}",
      "",
      "% ── Appendices ──────────────────────────────",
      "\\appendix",
      "\\chapter{Supplementary Proofs}",
      "\\chapter{Dataset Details}",
      "",
      "% ── Bibliography ────────────────────────────",
      "\\begin{thebibliography}{9}",
      "\\bibitem{smith2023} Smith, J. (2023). \\textit{Foundational paper}. Nature, 610, 1--8.",
      "\\end{thebibliography}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "masters-thesis",
    icon: "📚",
    title: "Master's Thesis",
    category: "Thesis",
    desc: "Streamlined thesis template for MSc/MEng — cleaner than PhD, still professional.",
    source: [
      "\\documentclass[12pt, a4paper]{report}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage{geometry}",
      "\\geometry{margin=2.5cm}",
      "\\usepackage{setspace}",
      "\\onehalfspacing",
      "\\usepackage{amsmath, amssymb}",
      "\\usepackage[hidelinks]{hyperref}",
      "\\usepackage{graphicx}",
      "\\usepackage{booktabs}",
      "",
      "\\begin{document}",
      "",
      "% ── Title page ──",
      "\\begin{titlepage}",
      "  \\centering",
      "  \\vspace*{2cm}",
      "  {\\large University Name}\\\\[0.5cm]",
      "  {\\large Department of XYZ}\\\\[2cm]",
      "  {\\Huge \\textbf{Your Thesis Title}}\\\\[1cm]",
      "  {\\large \\textit{Submitted in partial fulfillment of the}}\\\\",
      "  {\\large \\textit{requirements for the degree of}}\\\\[0.5cm]",
      "  {\\Large Master of Science}\\\\[2cm]",
      "  {\\large By: \\textbf{Your Name}}\\\\[0.5cm]",
      "  {\\large Supervisor: Prof. Name}\\\\[2cm]",
      "  {\\today}",
      "\\end{titlepage}",
      "",
      "\\chapter*{Abstract}",
      "\\addcontentsline{toc}{chapter}{Abstract}",
      "Write a concise summary of your thesis (200--400 words).",
      "",
      "\\tableofcontents",
      "",
      "\\chapter{Introduction}",
      "\\section{Problem Statement}",
      "\\section{Objectives}",
      "\\section{Report Structure}",
      "",
      "\\chapter{Background}",
      "\\section{Related Work}",
      "\\section{Theoretical Background}",
      "",
      "Some key equations:",
      "\\[",
      "  \\nabla^2 \\phi = -\\frac{\\rho}{\\varepsilon_0}",
      "\\]",
      "",
      "\\chapter{Approach}",
      "\\section{Design}",
      "\\section{Implementation}",
      "",
      "\\chapter{Evaluation}",
      "\\section{Experimental Setup}",
      "",
      "\\begin{table}[ht]",
      "  \\centering",
      "  \\caption{Results summary.}",
      "  \\begin{tabular}{lcc}",
      "    \\toprule",
      "    Metric & Baseline & Ours \\\\",
      "    \\midrule",
      "    Accuracy & 82\\% & \\textbf{91\\%} \\\\",
      "    Latency (ms) & 45 & 38 \\\\",
      "    \\bottomrule",
      "  \\end{tabular}",
      "\\end{table}",
      "",
      "\\chapter{Conclusion}",
      "\\section{Summary}",
      "\\section{Future Work}",
      "",
      "\\appendix",
      "\\chapter{Additional Results}",
      "",
      "\\begin{thebibliography}{9}",
      "\\bibitem{ref1} Author, A. (2022). \\textit{Paper title}. Conference, pp. 1--10.",
      "\\end{thebibliography}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "ieee-paper",
    icon: "📡",
    title: "IEEE Conference Paper",
    category: "Research",
    desc: "Two-column IEEE format ready for submission to conferences (IEEEtran class).",
    source: [
      "\\documentclass[conference]{IEEEtran}",
      "\\usepackage{amsmath,amssymb}",
      "\\usepackage{graphicx}",
      "\\usepackage{cite}",
      "\\usepackage{url}",
      "\\usepackage[hidelinks]{hyperref}",
      "",
      "\\begin{document}",
      "",
      "\\title{Title of Your IEEE Paper}",
      "",
      "\\author{",
      "  \\IEEEauthorblockN{First Author}",
      "  \\IEEEauthorblockA{Department of XYZ\\\\",
      "  University, City, Country\\\\",
      "  first.author@university.edu}",
      "  \\and",
      "  \\IEEEauthorblockN{Second Author}",
      "  \\IEEEauthorblockA{Department of ABC\\\\",
      "  University, City, Country\\\\",
      "  second.author@university.edu}",
      "}",
      "",
      "\\maketitle",
      "",
      "\\begin{abstract}",
      "This paper presents... (150 words max for IEEE). Summarize the problem,",
      "your approach, and key results clearly and concisely.",
      "\\end{abstract}",
      "",
      "\\begin{IEEEkeywords}",
      "machine learning, optimization, deep learning, neural networks",
      "\\end{IEEEkeywords}",
      "",
      "\\section{Introduction}",
      "Introduce the problem and your contributions.",
      "Recent work \\cite{author2023} has shown that...",
      "",
      "\\section{Related Work}",
      "Discuss related approaches and their limitations.",
      "",
      "\\section{Proposed Method}",
      "\\subsection{Problem Formulation}",
      "Let $\\mathbf{x} \\in \\mathbb{R}^d$ denote the input. We optimize:",
      "\\[",
      "  \\min_{\\theta} \\mathcal{L}(\\theta) = \\frac{1}{n}\\sum_{i=1}^{n}",
      "  \\ell(f_\\theta(\\mathbf{x}_i), y_i)",
      "\\]",
      "",
      "\\subsection{Algorithm}",
      "Describe your algorithm here.",
      "",
      "\\section{Experiments}",
      "\\subsection{Setup}",
      "We evaluate on [datasets]. All experiments use [hardware].",
      "",
      "\\subsection{Results}",
      "Table \\ref{tab:results} shows that our method achieves...",
      "",
      "\\begin{table}[ht]",
      "  \\centering",
      "  \\caption{Performance comparison.}",
      "  \\begin{tabular}{lcc}",
      "    \\hline",
      "    Method & Acc. (\\%) & FLOPs \\\\",
      "    \\hline",
      "    Baseline~\\cite{author2023} & 88.2 & 2.3G \\\\",
      "    \\textbf{Ours} & \\textbf{93.1} & 2.5G \\\\",
      "    \\hline",
      "  \\end{tabular}",
      "  \\label{tab:results}",
      "\\end{table}",
      "",
      "\\section{Conclusion}",
      "We proposed a method that achieves state-of-the-art results on [task].",
      "",
      "\\begin{thebibliography}{1}",
      "\\bibitem{author2023}",
      "A.~Author, B.~Author, ``Title of referenced paper,''",
      "\\textit{IEEE Trans. Pattern Anal.}, vol.~45, no.~1, pp.~1--10, 2023.",
      "\\end{thebibliography}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "research-proposal",
    icon: "💡",
    title: "Research Proposal",
    category: "Thesis",
    desc: "Structured research proposal for PhD applications, grants, or funding bodies.",
    source: [
      "\\documentclass[12pt, a4paper]{article}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage{geometry}",
      "\\geometry{margin=2.5cm}",
      "\\usepackage{setspace}",
      "\\onehalfspacing",
      "\\usepackage{amsmath}",
      "\\usepackage[hidelinks]{hyperref}",
      "\\usepackage{titlesec}",
      "",
      "\\title{\\textbf{Research Proposal}\\\\",
      "  {\\large Title of Your Proposed Research}}",
      "\\author{Candidate Name\\\\",
      "  {\\small Proposed Supervisor: Prof. Name}\\\\",
      "  {\\small Institution, Department}}",
      "\\date{\\today}",
      "",
      "\\begin{document}",
      "\\maketitle",
      "",
      "\\section{Research Overview}",
      "",
      "\\subsection{Background}",
      "Briefly introduce the research area and its importance.",
      "",
      "\\subsection{Problem Statement}",
      "Clearly state the gap in knowledge that your research will address.",
      "",
      "\\subsection{Research Questions}",
      "\\begin{enumerate}",
      "  \\item Primary: How does X affect Y in context Z?",
      "  \\item Secondary: Can method A scale to settings B?",
      "\\end{enumerate}",
      "",
      "\\section{Literature Review}",
      "",
      "Summarize key existing work and explain how your research builds on it.",
      "Key papers: \\cite{smith2023, jones2022}.",
      "",
      "\\section{Methodology}",
      "",
      "\\subsection{Research Design}",
      "Describe your overall approach (qualitative/quantitative/mixed).",
      "",
      "\\subsection{Methods}",
      "\\begin{itemize}",
      "  \\item Data collection: ...",
      "  \\item Analysis: ...",
      "  \\item Validation: ...",
      "\\end{itemize}",
      "",
      "\\subsection{Mathematical Approach}",
      "Describe any key equations or models if applicable:",
      "\\[",
      "  \\hat{y} = f(\\mathbf{x}; \\theta) + \\varepsilon, \\quad \\varepsilon \\sim \\mathcal{N}(0, \\sigma^2)",
      "\\]",
      "",
      "\\section{Timeline}",
      "",
      "\\begin{tabular}{ll}",
      "  Months 1--6   & Literature review, data collection \\\\",
      "  Months 7--18  & Model development and experiments \\\\",
      "  Months 19--30 & Analysis, writing, dissemination \\\\",
      "  Months 31--36 & Thesis writing and submission \\\\",
      "\\end{tabular}",
      "",
      "\\section{Expected Contributions}",
      "",
      "This research will contribute:",
      "\\begin{itemize}",
      "  \\item A new theoretical framework for...",
      "  \\item An empirical study demonstrating...",
      "  \\item Open-source tools enabling...",
      "\\end{itemize}",
      "",
      "\\section{Budget Justification}",
      "If applicable, justify funding requirements here.",
      "",
      "\\begin{thebibliography}{9}",
      "\\bibitem{smith2023} Smith, J. (2023). \\textit{Key paper}. Nature, 610, 1--8.",
      "\\bibitem{jones2022} Jones, A. (2022). \\textit{Related work}. ICML, pp. 1--10.",
      "\\end{thebibliography}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
];

export const CATEGORIES = ["All", "Thesis", "Research", "Career", "Slides", "Homework"];

