export interface Template {
  id: string;
  icon: string;
  title: string;
  category: string;
  desc: string;
  source: string;
}

export const TEMPLATES: Template[] = [
  {
    id: "article",
    icon: "📝",
    title: "Academic Article",
    category: "Research",
    desc: "Standard article with abstract, sections, math equations, and bibliography.",
    source: [
      "\\documentclass[12pt,a4paper]{article}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage{amsmath,amssymb,amsthm}",
      "\\usepackage{hyperref}",
      "\\usepackage{geometry}",
      "\\geometry{margin=2.5cm}",
      "",
      "\\title{\\textbf{Title of Your Paper}\\\\",
      "  \\large Subtitle or Affiliation}",
      "\\author{First Author\\thanks{Corresponding author: email@university.edu} \\and Second Author}",
      "\\date{\\today}",
      "",
      "\\begin{document}",
      "",
      "\\maketitle",
      "",
      "\\begin{abstract}",
      "This paper presents a study of... Write your abstract here, summarizing the main contributions, methodology, and results. Keep it concise — typically 150–300 words.",
      "\\end{abstract}",
      "",
      "\\section{Introduction}",
      "",
      "Write your introduction here. Reference prior work \\cite{smith2023} and state your contributions clearly.",
      "",
      "\\section{Methodology}",
      "",
      "Describe your methods. You can include equations:",
      "",
      "\\begin{equation}",
      "  E = mc^2",
      "\\end{equation}",
      "",
      "And more complex ones:",
      "",
      "\\[",
      "  \\int_0^\\infty e^{-x^2}\\,dx = \\frac{\\sqrt{\\pi}}{2}",
      "\\]",
      "",
      "\\subsection{Experimental Setup}",
      "",
      "Describe your experimental setup here.",
      "",
      "\\section{Results}",
      "",
      "Present your results. Consider adding tables and figures.",
      "",
      "\\section{Conclusion}",
      "",
      "Summarize your findings and future work.",
      "",
      "\\begin{thebibliography}{9}",
      "\\bibitem{smith2023} Smith, J. (2023). \\textit{A great paper}. Journal of Things, 42(1), 1--10.",
      "\\end{thebibliography}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "cv",
    icon: "👤",
    title: "Academic CV",
    category: "Career",
    desc: "Clean CV template for researchers and academics with publications section.",
    source: [
      "\\documentclass[11pt,a4paper]{article}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage{geometry}",
      "\\geometry{margin=2cm}",
      "\\usepackage{hyperref}",
      "\\usepackage{enumitem}",
      "\\setlist{noitemsep}",
      "\\pagestyle{empty}",
      "",
      "\\begin{document}",
      "",
      "{\\LARGE \\textbf{Your Name}}\\\\[0.3em]",
      "{\\large Researcher -- University Name}\\\\[0.2em]",
      "\\href{mailto:you@university.edu}{you@university.edu}",
      "+1 (555) 000-0000",
      "",
      "\\hrule\\vspace{0.5em}",
      "",
      "\\section*{Education}",
      "",
      "\\textbf{Ph.D. in Computer Science} \\hfill 2020 -- Present\\\\",
      "University Name, City, Country\\\\",
      "\\textit{Thesis: Title of your dissertation}",
      "",
      "\\textbf{M.Sc. in Mathematics} \\hfill 2018 -- 2020\\\\",
      "Another University, City, Country",
      "",
      "\\section*{Research Interests}",
      "",
      "Machine learning, optimization, numerical methods, scientific computing.",
      "",
      "\\section*{Publications}",
      "",
      "\\begin{enumerate}",
      "  \\item \\textbf{Your Name}, Co-Author. ``Paper Title.'' \\textit{Journal Name}, vol. 42, 2023.",
      "  \\item \\textbf{Your Name}, Co-Author. ``Conference Paper.'' \\textit{NeurIPS}, 2022.",
      "\\end{enumerate}",
      "",
      "\\section*{Experience}",
      "",
      "\\textbf{Research Intern} \\hfill Summer 2022\\\\",
      "Company / Lab Name, City\\\\",
      "Worked on relevant problems in the field.",
      "",
      "\\section*{Skills}",
      "",
      "\\textbf{Programming:} Python, Julia, MATLAB, C++\\\\",
      "\\textbf{Tools:} LaTeX, Git, Linux, Docker\\\\",
      "\\textbf{Languages:} English (fluent), French (native)",
      "",
      "\\section*{Awards}",
      "",
      "\\begin{itemize}",
      "  \\item Best Paper Award, SomeConference 2023",
      "  \\item Research Fellowship, University Name, 2021",
      "\\end{itemize}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "beamer",
    icon: "📊",
    title: "Beamer Presentation",
    category: "Slides",
    desc: "Clean Beamer slide deck with title slide, table of contents, and math.",
    source: [
      "\\documentclass{beamer}",
      "\\usetheme{Madrid}",
      "\\usecolortheme{seahorse}",
      "\\usepackage{amsmath,amssymb}",
      "",
      "\\title[Short Title]{Full Title of Your Presentation}",
      "\\subtitle{Subtitle or Conference Name}",
      "\\author{Your Name}",
      "\\institute{University or Department}",
      "\\date{\\today}",
      "",
      "\\begin{document}",
      "",
      "\\begin{frame}",
      "  \\titlepage",
      "\\end{frame}",
      "",
      "\\begin{frame}{Table of Contents}",
      "  \\tableofcontents",
      "\\end{frame}",
      "",
      "\\section{Introduction}",
      "",
      "\\begin{frame}{Motivation}",
      "  \\begin{itemize}",
      "    \\item Why is this problem important?",
      "    \\item What gap does this work address?",
      "    \\item Key challenges we overcome:",
      "    \\begin{itemize}",
      "      \\item Challenge 1",
      "      \\item Challenge 2",
      "    \\end{itemize}",
      "  \\end{itemize}",
      "\\end{frame}",
      "",
      "\\section{Method}",
      "",
      "\\begin{frame}{Our Approach}",
      "  \\begin{block}{Main Idea}",
      "    We propose a method based on the following key insight...",
      "  \\end{block}",
      "",
      "  The gradient descent update is:",
      "  \\[",
      "    x_{n+1} = x_n - \\alpha \\nabla f(x_n)",
      "  \\]",
      "",
      "  where $\\alpha$ is the learning rate.",
      "\\end{frame}",
      "",
      "\\section{Results}",
      "",
      "\\begin{frame}{Experimental Results}",
      "  Dataset A: Accuracy 94.2\\%, F1 Score 0.941\\\\",
      "  Dataset B: Accuracy 91.7\\%, F1 Score 0.918",
      "\\end{frame}",
      "",
      "\\section{Conclusion}",
      "",
      "\\begin{frame}{Conclusion}",
      "  \\begin{itemize}",
      "    \\item We presented a novel approach to...",
      "    \\item Our method outperforms baselines on X benchmarks",
      "    \\item Future work: extension to larger datasets",
      "  \\end{itemize}",
      "  \\vspace{1.5em}",
      "  \\centering \\Large \\textbf{Thank you! Questions?}",
      "\\end{frame}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "math-assignment",
    icon: "🧮",
    title: "Math Assignment",
    category: "Homework",
    desc: "Problem set template with theorem/proof environments and custom commands.",
    source: [
      "\\documentclass[12pt]{article}",
      "\\usepackage{amsmath,amssymb,amsthm}",
      "\\usepackage{geometry}",
      "\\geometry{margin=2.5cm}",
      "\\usepackage{enumitem}",
      "",
      "% Custom commands",
      "\\newcommand{\\R}{\\mathbb{R}}",
      "\\newcommand{\\N}{\\mathbb{N}}",
      "\\newcommand{\\Z}{\\mathbb{Z}}",
      "\\newcommand{\\eps}{\\varepsilon}",
      "",
      "% Theorem environments",
      "\\newtheorem{theorem}{Theorem}",
      "\\newtheorem{lemma}[theorem]{Lemma}",
      "\\theoremstyle{definition}",
      "\\newtheorem{definition}{Definition}",
      "",
      "\\title{Problem Set 3}",
      "\\author{Your Name}",
      "\\date{Due: \\today}",
      "",
      "\\begin{document}",
      "\\maketitle",
      "",
      "\\section*{Problem 1}",
      "",
      "Prove that every bounded sequence in $\\R^n$ has a convergent subsequence.",
      "",
      "\\textbf{Proof.}",
      "We proceed by induction on $n$.",
      "",
      "\\textbf{Base case} ($n=1$): By the Bolzano-Weierstrass theorem, every bounded sequence",
      "in $\\R$ has a convergent subsequence.",
      "",
      "\\textbf{Inductive step}: Assume the result holds for $\\R^{n-1}$. Let $(\\mathbf{x}_k)$",
      "be a bounded sequence in $\\R^n$. The projection onto the first coordinate is bounded in $\\R$,",
      "so it has a convergent subsequence by the base case. $\\square$",
      "",
      "\\section*{Problem 2}",
      "",
      "Let $f: \\R \\to \\R$ be differentiable. Show that if $|f'(x)| \\leq M$ for all $x$, then:",
      "",
      "\\[",
      "  |f(x) - f(y)| \\leq M|x - y| \\quad \\text{for all } x, y \\in \\R",
      "\\]",
      "",
      "\\textbf{Proof.}",
      "By the Mean Value Theorem, there exists $c$ between $x$ and $y$ such that",
      "$f(x) - f(y) = f'(c)(x-y)$.",
      "Taking absolute values gives $|f(x) - f(y)| \\leq M|x-y|$. $\\square$",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "letter",
    icon: "✉️",
    title: "Cover Letter",
    category: "Career",
    desc: "Professional cover letter for academic or industry job applications.",
    source: [
      "\\documentclass[11pt,a4paper]{article}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage{geometry}",
      "\\geometry{margin=2.5cm}",
      "",
      "\\begin{document}",
      "",
      "\\noindent",
      "\\textbf{Your Name}\\\\",
      "Department, University\\\\",
      "City, Country\\\\",
      "you@example.com",
      "",
      "\\vspace{1em}",
      "\\noindent \\today",
      "",
      "\\vspace{1em}",
      "\\noindent",
      "Hiring Manager\\\\",
      "Company / Department\\\\",
      "City, Country",
      "",
      "\\vspace{1em}",
      "\\noindent Dear Hiring Committee,",
      "",
      "I am writing to apply for the position of [Role] at [Organization].",
      "I am currently a [your status] at [institution], specializing in [your field].",
      "",
      "My research focuses on [describe your research in 1-2 sentences].",
      "I believe my background in [skills/areas] makes me a strong candidate for this position.",
      "",
      "During my time at [previous institution/company], I [achievement 1].",
      "Additionally, I [achievement 2].",
      "These experiences have equipped me with [skills] directly applicable to your team's work.",
      "",
      "I am particularly drawn to [Organization] because [specific reason].",
      "I am confident that I could contribute meaningfully to [specific project or goal].",
      "",
      "I have attached my CV and would welcome the opportunity to discuss further.",
      "",
      "\\vspace{1em}",
      "\\noindent Sincerely,\\\\[2em]",
      "\\noindent \\textbf{Your Name}",
      "",
      "\\end{document}",
    ].join("\n"),
  },
  {
    id: "physics",
    icon: "⚛️",
    title: "Physics Lab Report",
    category: "Research",
    desc: "Structured lab report with error analysis, tables, and SI units.",
    source: [
      "\\documentclass[12pt,a4paper]{article}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage{amsmath,amssymb}",
      "\\usepackage{siunitx}",
      "\\usepackage{booktabs}",
      "\\usepackage{geometry}",
      "\\geometry{margin=2.5cm}",
      "",
      "\\title{Lab Report: Measurement of Gravitational Acceleration}",
      "\\author{Student Name \\\\ Partner Name}",
      "\\date{\\today}",
      "",
      "\\begin{document}",
      "\\maketitle",
      "",
      "\\section{Objective}",
      "",
      "Determine the local gravitational acceleration $g$ using a simple pendulum,",
      "and compare the result to the accepted value of",
      "$g = \\SI{9.81}{m/s^2}$.",
      "",
      "\\section{Theory}",
      "",
      "For small oscillations, the period $T$ of a simple pendulum of length $L$ is:",
      "",
      "\\[",
      "  T = 2\\pi\\sqrt{\\frac{L}{g}}",
      "\\]",
      "",
      "Solving for $g$:",
      "",
      "\\[",
      "  g = \\frac{4\\pi^2 L}{T^2}",
      "\\]",
      "",
      "\\section{Data}",
      "",
      "\\begin{table}[h]",
      "\\centering",
      "\\begin{tabular}{ccc}",
      "\\toprule",
      "Trial & Length $L$ (m) & Period $T$ (s) \\\\",
      "\\midrule",
      "1 & 0.500 & 1.421 \\\\",
      "2 & 0.500 & 1.419 \\\\",
      "3 & 0.500 & 1.423 \\\\",
      "\\midrule",
      "Mean & 0.500 & 1.421 \\\\",
      "\\bottomrule",
      "\\end{tabular}",
      "\\caption{Pendulum period measurements at fixed length $L = \\SI{0.500}{m}$.}",
      "\\end{table}",
      "",
      "\\section{Results}",
      "",
      "Using $L = \\SI{0.500}{m}$ and $T = \\SI{1.421}{s}$:",
      "",
      "\\[",
      "  g = \\frac{4\\pi^2 \\times 0.500}{(1.421)^2} = \\SI{9.78}{m/s^2}",
      "\\]",
      "",
      "\\section{Error Analysis}",
      "",
      "The percentage error relative to the accepted value is:",
      "\\[",
      "  \\text{error} = \\frac{|9.78 - 9.81|}{9.81} \\times 100\\% = 0.31\\%",
      "\\]",
      "",
      "\\section{Conclusion}",
      "",
      "The measured value $g = \\SI{9.78}{m/s^2}$ agrees with the accepted value",
      "to within experimental uncertainty. Main sources of error: air resistance,",
      "timing reaction delay, and non-zero amplitude.",
      "",
      "\\end{document}",
    ].join("\n"),
  },
];

export const CATEGORIES = ["All", ...Array.from(new Set(TEMPLATES.map(t => t.category)))];
